docs/installation.md

* The installation instruction has been made easier to follow by introducing bullet lists where the linear flow is temporarily branched off into separate paths for different database engines or operating systems.
* Placeholder sections for SQLite has been added.
* Notes about unsupported stuff have been replaced by notes about missing instructions.
* Notes have been updated to use proper formatting.
* The fact that sudo is only needed for administrative tasks has been clarified.

Various improvements

---

lib/Zonemaster/Backend/DB/MySQL.pm
lib/Zonemaster/Backend/DB/PostgreSQL.pm

Replaced JSON with JSON::PP in modules where JSON::PP, but not JSON, was loaded. This was meant to be fixed in PR #277.
Affected modules: 
* Zonemaster/Backend/DB/MySQL.pm
* Zonemaster/Backend/DB/PostgreSQL.pm

Replaced JSON with JSON::PP in modules

---

lib/Zonemaster/Backend/DB/MySQL.pm
lib/Zonemaster/Backend/DB/PostgreSQL.pm
lib/Zonemaster/Backend/TestAgent.pm
script/create_db_mysql.pl
script/create_db_postgresql_9.3.pl
share/initial-mysql.sql
share/initial-postgres.sql

Fix issue 292

---

share/zm-backend.sh-mysql
share/zm-backend.sh-postgresql
share/zm-centos.sh-mysql
share/zm-centos.sh-postgresql

The language setting via JSON RPC does not work if LANGUAGE is set to something, at least in some OSs. With this fix, to be safe some environment variables are unset, and LC_CTYPE is set to the default locale. With this setting it should work, and it will not be in conflict with anything.
The PR is a work-around for the issue described in issue #350, but this should NOT be considered to be a solution.

Adjusting the locale environment before the daemons are started

---

docs/Installation.md

Fixes #358.
This also includes a drive-by simplification of a neighbouring line.
I've successfully tested the Debian instruction.
@sandoche2k Would you test the CentOS instruction? I'll start doing it myself as well, but I have a hunch that you'll be able to make it quicker.

 Avoid known filenames in world-writable directory

---

MANIFEST

#362 removed some files from the distribution, but did not update the MANIFEST accordingly.

Clean up MANIFEST after #362

---

MANIFEST

#363 combined two pairs of scripts into two separate scripts but failed to update the MANIFEST accordingly. This PR fixes that.

Clean up MANIFEST after #363

---

lib/Zonemaster/Backend/Config.pm
lib/Zonemaster/Backend/Config/DCPlugin.pm
script/zonemaster_backend_testagent

Make the start and restart commands of zonemaster_backend_testagent
fail before daemonization if the configured database is
inaccessible. This enables us to make service scripts that properly
report errors when the configured database engine isn't installed and
when there's a problem with the database connection configuration.
If the database connection fails early, zonemaster_backend_testagent
exits with a non-zero status and an error message to stderr.

TestAgent: Fail early if database is inaccessible

---

docs/Installation.md

The line it refers to doesn't exist anymore.

Remove obsolete to-do note

---

docs/Installation.md

Adds explicit links from the end of OS-specific sections to the common part at the bottom of the document. This makes the document easier to follow when installing.

Make the installation instruction easier to follow

---

lib/Zonemaster/Backend/RPCAPI.pm

* Corrected error message when a non-ascii domain label cannot be converted to A-label, i.e. it is not a valid IDNA label.
* Corrected error message when there is no support for non-ascii domain labels, i.e. zonemaster-ldns is not built with libidn support.

Corrected error message for IDN

---

docs/Installation.md

This change unifies the duplicated sanity check sections and places it among the post-installation matters where it belongs.

Deduplicate sanity checks across OSes

---

docs/Installation.md

Now that the API test has been decoupled from the OS installations, the phrasing needs an update. "Sanity" check does not feel appropriate in these instructions. It is just a test that it works, not a test of sanity.

Installation instructions

---

docs/API.md

Update the API Documentation to deprecate the method "validate_syntax"

Deprecate validate_syntax

---

docs/API.md

Deprecate validate_syntax. PR based on the develop branch.
No need to a feature API branch since there are no breaking change and all will be done for the same release (this one).

Deprecate validate_syntax (from develop branch)

---

docs/API.md
lib/Zonemaster/Backend/RPCAPI.pm
script/zonemaster_backend_rpcapi.psgi

Creation of get_host_by_name method, and put get_ns_ips as an alias.
Deprecate get_ns_ips in the API code and doc.
Issue #163

"get_ns_ips" should have an alias to "get_host_by_name"

---

Makefile.PL

Update JSON::Validator from 2.06 to 2.07 which have our fix.

Update JSON::Validator from 2.06 to 2.07

---

lib/Zonemaster/Backend/RPCAPI.pm

Replace to empty string is not enough, we need to delete the keys.

delete user info from start_domain request

---

lib/Zonemaster/Backend/RPCAPI.pm
lib/Zonemaster/Backend/Validator.pm

Fix issue #431 - Allow null, string, number as id in json rpc request

Fix issue #431 - Allow null, string, number as id in json rpc request

---

docs/Installation.md

FreeBSD sed doesn't support the `\b` word boundary syntax.
FreeBSD sed -i option requires an argument.

Update sed commands on FreeBSD

---

README.md
docs/Installation.md
share/zm_rpcapi-bsd
share/zm_testagent-bsd

* Consistency uses /usr/local/etc/zonemaster (instead of /etc/zonemaster)
in all four files for FreeBSD
* Use cpanm instead of cpan in Installation.pm
* Minor updates for FreeBSD in Installation.pm

Updates for FreeBSD

---

lib/Zonemaster/Backend/Config.pm
lib/Zonemaster/Backend/Config/DCPlugin.pm
lib/Zonemaster/Backend/DB.pm
lib/Zonemaster/Backend/DB/MySQL.pm
lib/Zonemaster/Backend/DB/PostgreSQL.pm
lib/Zonemaster/Backend/DB/SQLite.pm
lib/Zonemaster/Backend/RPCAPI.pm
lib/Zonemaster/Backend/TestAgent.pm
script/create_db_mysql.pl
script/create_db_postgresql_9.3.pl
script/crontab_job_runner/execute_tests.pl
script/patch_db_mysql_for_backend_DB_version_lower_than_1.0.3.pl
script/patch_db_postgresq_for_backend_DB_version_lower_than_1.0.3.pl
script/zonemaster_backend_testagent
share/backend_config.ini

Fixes issue #405
Adds the profiles feature to the backend.
Changes the way the config file is read to allow passing it as a parameter to the test agent.

Fix code part of issue #405 - use the new profiles feature of the Zonemaster-Engine

---

.travis.yml

This is an attempt to make Backend run its tests against the Engine develop branch. This is needed as the profiles feature is a breaking change.

Build against Engine develop branch

---

.travis.yml

I expect Travis to start failing for Backend once zonemaster/zonemaster-ldns#72 is merged. This PR should pass both before and after merging zonemaster/zonemaster-ldns#72.

Provide configure-time-deps for Zonemaster::LDNS

---

share/initial-postgres.sql

update initial sql script for postgres. Give ownership of main table to zonemaster instead of postgres.
Fix #503

update initial sql script for postgres 

---

docs/Installation.md

When you create the user, a group with the same name is automatically created and "attached" to the created user, if you do not specify the group. Two commands are collapsed into one.

Simplify the installation commands for FreeBSD

---

docs/Installation.md

This will print an error message if curl is unable to connect to the RPCAPI. It will also print all files and directories created (using install) - this is nice when cutting and pasting whole sequences of commands into the terminal.

Give more feedback to the user in case something goes wrong

---

Makefile.PL
docs/Installation.md
lib/Zonemaster/Backend/Translator.pm
share/zm-backend.sh

This change places the responsibility for how to switch languages on Engine while keeping the responsibility of when that should be done in the Backend.
In combination with zonemaster/zonemaster-engine#562 it enables choosing translation language in requests to the RPCAPI on FreeBSD 11. However once you've chosen a language it gets stuck on that language no matter what language you ask for in subsequent requests. Compare that with the current behavior where the language is simply stuck on English. In my view this is an improvement.
Curiously, when I tested this on FreeBSD 11 I was consistently able to choose different languages twice, but then it got stuck on the second language. I haven't looked into why this happens.
Other OSes are unaffected - I've only verified this on FreeBSD 12 and …

Partial fix for translation on FreeBSD 11

---

lib/Zonemaster/Backend/Config.pm
lib/Zonemaster/Backend/Config/DCPlugin.pm
lib/Zonemaster/Backend/DB.pm
lib/Zonemaster/Backend/DB/MySQL.pm
lib/Zonemaster/Backend/DB/PostgreSQL.pm
lib/Zonemaster/Backend/DB/SQLite.pm
lib/Zonemaster/Backend/RPCAPI.pm
lib/Zonemaster/Backend/TestAgent.pm
script/zonemaster_backend_rpcapi.psgi
script/zonemaster_backend_testagent
t/test01.t
t/test_validate_syntax.t

Fixes #528. The further improvement with reloading on SIGHUP is not included here. I'll create a separate issue for that.
This PR also takes a step towards #214 by introducing a log entry for loading of the config file (which wasn't feasible before with the relentless config reloading), and also beginning and end entries for the "pre-flight check".

Avoid reloading configuration in Test Agent

---

lib/Zonemaster/Backend/RPCAPI.pm

This works around the deprecation warning reported in #507. The offending code is in JSON::Validator::Joi::validate. I created mojolicious/json-validator#165 to fix it. This PR inlines the fixed code as a stop-gap until a fixed version of JSON-Validator is available on all supported platforms. I've added a comment about reinstating the call to JSON::Validator::Joi::validate and when it is appropriate to do so.

Work around deprecation warning

---

Makefile.PL
lib/Zonemaster/Backend/RPCAPI.pm

The crash occurs in a workaround for a bug in JSON::Validator. The bug was fixed in JSON::Validator 3.12 and we don't need the workaround anymore. This PR reverts the workaround and bumps the requirement for JSON::Validator.
Fixes #559.

Fix crash in RPCAPI

---

MANIFEST
docs/Installation.md
share/tmpfiles.conf

I had strange behaviors with the RPCAPI sometimes not starting and when I dug into it I stumbled upon a solution to the reboot problem. The trick is to tell systemd-tmpfiles to (re)create `/var/run/zonemaster` at start up. The directory goes away because it resides on a tmpfs partition.
Fixes #513.

Compatibility with systemd-tmpfiles

---

docs/Configuration.md
docs/Installation.md

The `mysql-server` package isn't available on Debian 10, but `mariadb-server` is available on all of Debian 9 (stretch), Debian 10 (buster), Ubuntu 16.04 (xenial) and Ubuntu 18.04 (bionic), so this PR switches over to install that package instead.
I removed the step to verify the PostgreSQL version because we don't support anything that gives you PostgreSQL <= 9.2 by default.
I updated the config file editing steps to make the result look more tidy.

Installation on Debian

---

docs/Installation.md

Fixes #589. 
This makes sure /lib/lsb/init-functions is installed on CentOS. We depend on those for zm-rpcapi.lsb and we're using that on CentOS.

Add forgotten dependency

---

docs/Installation.md

Extends the scope of the solution in #565 to also encompass CentOS.
Fixes #574.

Compatibility with systemd-tmpfiles on CentOS

---

lib/Zonemaster/Backend/Translator.pm

Resolves issue #593. 
This fix has been successfully tested in FreeBSD 12.1. In FreeBSD 11.3 it does not help, so that version remains broken.
CentOS, Debian and Ubuntu must be tested without and with this fix. Does it make any difference for any of those OSs? Does it create any problem?

Fix for translation on FreeBSD 12.1.

---

docs/Installation.md

Installation failed because Backend depends on a certain set of locales - namely en_US.UTF-8, sv_SE.UTF-8, fr_FR.UTF-8 and da_DK.UTF-8. If they're not present Backend crashes. In particular this happens when tests are run at installation time, causing the installation to abort. This PR fixes that problem by making sure the locales are installed.
This PR also includes a couple of other small improvements.

Debian installation

---

docs/Installation.md

* Added missing reference in the installation document to the database upgrade steps that might be needed when upgrading Zonemaster-Backend.
* Cleaned up the installation instruction for PostgreSQL under CentOS.
* Added missing reference to documentation of the Backend configuration (.ini) file from FreeBSD.

Update installation instruction

---

MANIFEST.SKIP
script/zmb
script/zmtest

Over a couple of years I've been cultivating a two helper programs that I've been using during development of the Backend. They've been a huge help in my work. Over time they've become easier to use and now I believe they've reached a point where other people should be able to use them without much trouble, even though the documentation is scant.
`zmb` is a tool for sending single requests to the RPCAPI. I deliberately made it possible to send invalid requests in order to try out the behavior of the RPCAPI in the presence of such. Also it only covers the most common commands and the most common parameters. I simply added things as I needed them.
`zmtest` is a synchronous client for running a test though the asynchronous Backend. I just starts a tests, polls it until its at progress 100 …

Add experimental CLI tools for backend

---

docs/API.md
docs/Configuration.md
lib/Zonemaster/Backend/Config.pm
lib/Zonemaster/Backend/RPCAPI.pm
lib/Zonemaster/Backend/Translator.pm
lib/Zonemaster/Backend/Validator.pm
script/zonemaster_backend_rpcapi.psgi
share/backend_config.ini
share/travis_mysql_backend_config.ini
share/travis_postgresql_backend_config.ini
share/travis_sqlite_backend_config.ini
t/test01.t
t/test_DB_backend.pl

This PR tries to handle the following issues in Zonemaster-Backend when it comes to selecting language for translation.
1. The API documentation is unclear if field `language` is mandatory in RPCAPI method `get_test_results` but in the implementation it is mandatory.
2. The string that can be used in the `language` field above can be quite long and can contain a broad range of characters, but in practice only the two first characters are considered. The rest is ignored.
3. If the two first characters do not match a supported language, then the error is just silently ignored, and the messages are shown untranslated (from English).
* The GUI actually just uses a string of two characters, "da", "en", "fr" or "sv".
4. To add support for a new language or to remove support for a some language …

Updated language specification handling

---

docs/Configuration.md
share/backend_config.ini

There are still traces of previous feature GEOLOCATION in default .ini file and documentation. Since the feature is long gone, these traces will be removed with this update. This resolves issue #607.

Removed unused GEOLOCATION

---

docs/Installation.md
share/freebsd-pwd.conf

Current installation instruction gives the zonemaster user a UID and a GID that are meant for normal users, not system users. For system users there are UIDs and GIDs reserved for specific programs (packages) and UIDs/GIDs that are still free. This patch will make the instruction give the zonemaster user a UID/GID that is from the free space. When Zonemaster-Backend is packaged for FreeBSD it could get a fixed UID/GID.
Read [here][porters-handbook-users-and-groups] about UIDs and GIDs for applications ported to FreeBSD.
To see the current status of the list of booked and free UIDs and GIDs go to [FreeBSD ports] and scroll down to `GIDs` and `UIDs` and select the revision number for the files.
[porters-handbook-users-and-groups]: https://www.freebsd.org/doc/en_US.ISO8859-1/books/porters-han …

System user UID/GID for zonemaster user/group under FreeBSD

---

lib/Zonemaster/Backend/RPCAPI.pm
t/test_DB_backend.pl

Travis was broken by zonemaster/zonemaster-engine#764. This fixes it again.
While this change works AFAICT, it doesn't seem like the best idea to use basic00 to check name and label length.

Fix failing test

---

Makefile.PL
docs/Installation.md

This a step towards resolving #449. It also speeds up installation on CentOS.
The Zonemaster-Engine installation instruction already adds the EPEL repo. This merely takes advantage of that.
Consideration has been taken to the fact that EPEL has somewhat different sets of packages for CentOS 7 and CentOS 8.
Edit: A couple of the packages aren't available through EPEL on CentOS 8, but they are available through the PowerTools repository, which we're also already prescribing in Zonemaster-Engine.

Install dependencies from EPEL instead of CPAN

---

lib/Zonemaster/Backend/RPCAPI.pm
lib/Zonemaster/Backend/Validator.pm

This is a silly workaround for a deprecation without a documented migration path.
Fixes #624.

Fix warning

---

share/zmb
share/zmtest

Adds `zmtest --lang LANG` option.
This also includes some small fixes remotely related documentation.
Implements part of #628.

Language option for zmtest

---

Makefile.PL
docs/Installation.md
lib/Zonemaster/Backend/RPCAPI.pm

Net::IP::XS will still be used (via Zonemaster::Engine::Net::IP) if it's installed.
Works towards solving #449 and completely fixes #193.

Remove direct dependency on Net::IP::XS

---

script/zonemaster_backend_rpcapi.psgi

In #638 I included a commit removing Plack::Middleware::Debug from the installation instruction in the belief that it wasn't used. It turns out that it is in fact being used. At least in a technical sense, though I'm not sure if it actually did anything.
In any case it doesn't seem to me like something we would want to enable in production installations. This PR goes ahead an really removes the use of Plack::Middleware::Debug.
I set the priority to high because at the moment the develop branch installation instruction doesn't install Plack::Middleware::Debug but when you start the RPCAPI the module is loaded. And we don't want to have it like that in the release.

Deploy without debug middleware

---

docs/API.md
docs/Configuration.md
docs/Installation.md
share/backend_config.ini
share/travis_mysql_backend_config.ini
share/travis_postgresql_backend_config.ini
share/travis_sqlite_backend_config.ini

The language strings for Norwegian, nb_NO and nb, are added to documentation and configuration to activate the support of that language as will be added to Engine by next release.

Activate Norwegian in Backend

---

script/zonemaster_backend_testagent
share/zm-rpcapi.lsb
share/zm-testagent.lsb

Make TestAgent write its logs to STDOUT when started with `zonemaster_backend_testagent --logfile=-`.
The log format is also different in this mode. In particular it avoids tagging each line with timestamp and pid, on the assumption that the consumer does that if needed. As it stands systemd does add timestamps and pids.
Fixes #612.

TestAgent support for logging to STDOUT

---

share/zmtest

The zmtest --lang option is broken. This fixes it.

Fix broken zmtest --lang option

---

script/zonemaster_backend_rpcapi.psgi

This fixes #640 in a minimalist way. We do get logging but the severity threshold is hard-coded to "warning".
For the moment we want to avoid setting it any lower because the config module keeps repeating that it reloaded the config file. This happens a lot!
Once we have the config reloading under control we also want the ability to configure the logging severity threshold, but that's for another time.
All the new dependencies added here are already being used in the test agent.

Attach adapter to Log::Any in RPCAPI

---

lib/Zonemaster/Backend/Translator.pm

I think I've got this figured out now.
* `$entry->{string}` never seems to exist, but  `Zonemaster::Engine::Logger::Entry::string` does exist, and it actually makes sense to call that on proper `Z::E::L::Entry` objects.
* Calling bless to get an `Z::E::L::Entry` object doesn't work because the object doesn't get properly initialized we end up crashing. Instead we should just be good citizens and call `Z::E::L::Entry::new`.
* The check of `Z::E::Translator::data` is kind of useless. The `Z::E::T::translate_tag` performs essentially the same check and returns $entry->string if the check fails. It's better to just use the `Z::E::T::translate_tag` return value.
* The early return was unfortunate because that code path failed to reset the locale, so I fixed that as well.
Fixes #631.

Fix warning in RPCAPI

---

lib/Zonemaster/Backend/RPCAPI.pm
lib/Zonemaster/Backend/Translator.pm

Handle the language parameter once per request in Z::B::RPCAPI::get_test_results instead of once per message. It also removes a call to Z::E::Translator::data that's useless after Z::B::Translator::translate_tag was updated in #649.

Clean up Zonemaster::Backend::Translator::translate_tag

---

docs/API.md

Fixes issue #647 
Fix inconsistencies between text and regex in the API documentation for _Client id_, _Client version_ and _Username_.

Fix API documentation

---

docs/Installation.md
share/zmtest

I ran into a bug when trying to use `zmtest` in the smoke test.
For unknown reasons the message strings in the JSON output end with "\n". In `zmtest` we process the output through echo and jq. Echo interprets escape sequences by default. New-line characters aren't allowed in JSON. And jq throws up on invalid JSON. So zmtest crashes.
This PR:
1. Makes zmtest not interpret escape sequences in the JSON output.
2. Makes zmtest print the testid earlier to make sure it gets printed even the program crashes during result processing.
3. Makes the installation instruction smoke test use zmtest.
An old copyright statement is also removed.

Updated smoke test

---

share/zmtest

This is an improvement over the diagnostics given in #661.

Improved diagnostics from zmtest when zmb gives non-JSON output

---

t/test01.t

Make the unit test use the default ini file by setting the environment variable to that to prevent installed ini file to be used.
Resolves issue #670.

Resolve issue #670

---

t/test01.t
t/test_validate_syntax.t

Updates  `t/test_validate_syntax.t` to ensure that `/etc/zonemaster/backend_config.ini` is not used for the unit test, but rather the default `backend_config.ini` that comes with the installation. (Unless the environment variable is explicitly set.) This resolves issue #677.
This is the same solution as been implemented in `t/test01.t` by #671. 
Also, two smaller editorial updates have been implemented in `t/test01.t`, one of which comes from a [comment] to #671. 
[comment]: https://github.com/zonemaster/zonemaster-backend/pull/671#pullrequestreview-532286870

Update unit tests (resolve #677)

---

share/zmb
share/zmtest

The zm tools (zmb and zmtest) are good tools for querying the backend directly from the command line. Here those tools are extended with more functions.
* Add support for method `profile_names` in `zmb`
* Add support for method `get_language_tags` in `zmb`
* Add support for "profile" in method `start_domain_test` in `zmb`
* Add support for "profile" in `zmtest`

Extended zm tools

---

lib/Zonemaster/Backend/TestAgent.pm
script/zonemaster_backend_testagent

This resolves #682 by moving the setting of IPv4 and IPv6 enabled/disabled until the profile has been loaded in TestAgent.pm.
Second commit is just a small fix of POD in `script/zonemaster_backend_testagent` (unrelated to above).

Resolves issue where selected profile overrides IPv4/6 setting in Backend

---

docs/Configuration.md

Add documentation to all backend keys as found in the `/lib/Zonemaster/Backend/Config.pm` file.
It appears that some keys are not used anywhere in the code.
This addresses #520 
This is a work in progress, some used keys are not documented yet.

Document all backend config keys

---

lib/Zonemaster/Backend/Config.pm
share/backend_config.ini
share/travis_mysql_backend_config.ini
share/travis_postgresql_backend_config.ini
share/travis_sqlite_backend_config.ini

Some properties defined in the .ini files are read by the Config.pm file but not used anywhere in the code.
As stated in https://github.com/zonemaster/zonemaster-backend/issues/273#issuecomment-701499400, they can be removed safely.
Closes #273

Remove unused configuration properties

---

docs/Configuration.md

Deprecate `force_hash_id_use_in_API_starting_from_id` in preparation for #691.

Deprecate force_hash_id_use_in_API_starting_from_id

---

MANIFEST
MANIFEST.SKIP
Makefile.PL
docs/Installation.md
script/zmb
script/zmtest

Solves #687.
Since the tools are being properly installed the dependencies that needs to be reflected in the dependencies. AFAICT we don't depend on curl anymore, so I'm removing that from the installation instruction. The GettingStarted document still uses curl but it has a separate note about installing it so we shouldn't need to consider that in the installation instruction.

Proper installation of zmtest and zmb

---

docs/Installation.md

PR #690 added support for SQLite as database engine. This PR adds installation instructions and resolves issue #177.
* Adds installation instructions for using SQLite as database engine for all OSs.
* Smaller update of installation instructions for the other database engines to make it possible to change between engines.

Installation instruction for SQLite

---

docs/Installation.md

install() command has incorrectly "-u" instead of "-o". This PR corrects that.
Makes sure the SQLite database is owned by zonemaster user.

Corrects Installation instruction for FreeBSD

---

docs/Installation.md

This PR:
* aligns locale generation with CLI installation document
* apply relevant changes from Centos section to Debian (inspired from https://github.com/zonemaster/zonemaster-backend/pull/696)
* install databases before configuring Zonemaster
* fix incorrect option
* fix database ownership

Update Debian installation instructions

---

share/zm_testagent-bsd

When backend uses SQLite the rc system places zm_testagent to be started before the network, which does not work well, and testagent does not get started. This PR requires the network to be up before zm_testagent is run.

Fixes correct start order at start-up

---

docs/Configuration.md
lib/Zonemaster/Backend/Config.pm
lib/Zonemaster/Backend/RPCAPI.pm
share/backend_config.ini

When creating a new test through RPCAPI it will first check if there is a recent test with the same test parameters. If so, and that test is not too old, a new test will not be created, instead the test result for that recent test will be reused.
As it is now, "not too old" is hard-coded to 10 minutes. That is probably a good choice in most cases, but sometimes that is too short and sometimes too long. This PR makes that configurable.
As a side effect, this PR sorts the methods in the "[ZONEMASTER]" section from the ini file in `lib/Zonemaster/Backend/Config.pm` and also adds POD documentation to those methods.

 Make age for reused test configurable 

---

docs/Installation.md

This directory creation is handled by tmpfiles.
Kudos to @matsstralbergiis for spotting this.

Clean up obsolete command

---

lib/Zonemaster/Backend/DB/PostgreSQL.pm

In may 2019 @sandoche2k said we should wait until the next release before removing this. I think it's safe to do it now.
Fixes #490.

Clean up commented out code

---

lib/Zonemaster/Backend/Config.pm

#692 adds a new parameter. However not specifying its value will give the following message in `t/test01.t` (see [Travis output from the PR](https://travis-ci.org/github/zonemaster/zonemaster-backend/jobs/761422347#L2269)) :
```
Use of uninitialized value $val in numeric gt (>) at /home/travis/build/zonemaster/zonemaster-backend/build_dir/lib/Zonemaster/Backend/Config.pm line 331.
```
This PR passes the default value (set to 600 seconds = 10 minutes) to the [`val()`](
https://metacpan.org/pod/Config::IniFiles#val-($section,-$parameter-%5B,-$default%5D-)) call if the the parameter `age_reuse_previous_test` does not exist.

Fix unitialized value

---

lib/Zonemaster/Backend/DB/SQLite.pm

This properly initialized the SQLite handle to throw exceptions on error instead of just setting $DBI::errstr and returning an error value.
Fixes #722.

Properly initialize SQLite handle

---

lib/Zonemaster/Backend/DB/SQLite.pm

Currently SQLite `get_test_history` does not behave exactly as the MySQL and PostgreSQL equivalent functions.
This PR fixes that :
* the return `id` is now either the `hash_id` or the `id` based on `force_hash_id_use_in_API_starting_from_id` parameter in the config file
* `overall_result` is now present in the output
There is an issue #691 currently discussing on a possible removal of `force_hash_id_use_in_API_starting_from_id`. This PR adds it in SQLite to offer the same behavior as with other databases (and because of another PR to add SQLite to `t/test_DB_backend.pl` - #716).

SQLite: harmonize get_test_history with MySQL and PostgreSQL

---

docs/Configuration.md
lib/Zonemaster/Backend/Config.pm
lib/Zonemaster/Backend/DB.pm
lib/Zonemaster/Backend/DB/MySQL.pm
lib/Zonemaster/Backend/DB/PostgreSQL.pm
lib/Zonemaster/Backend/DB/SQLite.pm
share/travis_mysql_backend_config.ini
share/travis_postgresql_backend_config.ini
t/test_DB_backend.pl

This PR resolves issue #691. The use of configuration key "force_hash_id_use_in_API_starting_from_id" has been deprecated by #694.
This PR simplifies the database engine codes considerable and removes a feature that we see no real use of.

Remove configuration that allows non-hash test ID

---

docs/API.md
lib/Zonemaster/Backend/Validator.pm

This is a follow-up to #726 and should be merged if and only if #726 is merged and directly after. Also see https://github.com/zonemaster/zonemaster-backend/pull/726#issuecomment-803972024.

Require test ID to be 16 character "hash_id" in all input

---

docs/Configuration.md
lib/Zonemaster/Backend/Config.pm
lib/Zonemaster/Backend/RPCAPI.pm
lib/Zonemaster/Backend/TestAgent.pm
script/zonemaster_backend_rpcapi.psgi
script/zonemaster_backend_testagent
t/test01.t
t/test_DB_backend.pl
t/test_validate_syntax.t

This PR is about loading the `backend_config.ini` file only once, at daemon startup for RPCAPI and TestAgent.
* it makes mandatory to pass a `config ref` as parameter to each  RPCAPI and TestAgent constructor (die otherwise)
* use this `config ref` everywhere instead of loading a new config
* remove the possibility to pass and load a module from constructor parameter, add a layer to check the validity of the input and then import the module (or die)
* do some refactoring and code formatting
Addresses #651, #674
_Remark:_ one commit (fd7a7f3 ) is only about reformatting (replacing tabs by 4 spaces and removing trailing spaces) 
Before, the RPCAPI was loading the ini file on every API calls. This can be highlighted by running the following steps :
1. create a valid `backend_config.ini` file …

Load ini file at RPCAPI and TestAgent startup only

---

lib/Zonemaster/Backend/DB/SQLite.pm

With MySQL and PostgreSQL the `test_results` method converts the `creation_time` to UTC before returning it because it is stored in the local timezone. SQLite already stores the timestamp in UTC according to https://www.sqlite.org/lang_createtable.html
> If the default value of a column is CURRENT_TIME, CURRENT_DATE or CURRENT_TIMESTAMP, then the value used in the new row is a text representation of the current UTC date and/or time.
Therefore SQLite should not convert its `creation_time` field before returning it to be consistent with other databases. (I realize the documentation does not say anything on the timezone to use, I think this should be updated).
Independently to this PR, create a test with the PostgreSQL database and retrieve its `creation_time` :
```
$ date; zmb …
```

SQLite: keep creation_time in UTC in test_results

---

lib/Zonemaster/Backend/RPCAPI.pm
t/test_validate_syntax.t

This re-enables the domain name validation we had back in 5.0.2.
With these changes the error response for invalid domain names caught by _check_domain is "Internal server error". This is less than great, but at least it's much better than accepting invalid strings.
Fixes #724.

Fix logical type errors

---

lib/Zonemaster/Backend/RPCAPI.pm

Some RPCAPI methods require a `params` object. However not providing it results in an `Internal error` :
```
$ curl -sS -H "Content-Type: application/json" -d '{"jsonrpc": "2.0", "id": 1, "method": "get_data_from_parent_zone"}' http://localhost:5000/ | jq .
{
"id": 1,
"error": {
"message": "Internal error 006 \n",
"code": -32603
}
}
```
But providing an erroneous `params` object give better feedback (the `domain` property is missing) :
```
$ curl -sS -H "Content-Type: application/json" -d '{"jsonrpc": "2.0", "id": 1, "method": "get_data_from_parent_zone", "params": {}}' http://localhost:5000/ | jq .
{
"error": {
"message": "Invalid method parameter(s).",
"code": "-32602",
"data": "/domain: Missing property.\n"
},
"id": null
}
```
Looking at the code, a …

RPCAPI catch error on missing params object

---

docs/Configuration.md
docs/Installation.md
lib/Zonemaster/Backend/Config.pm
lib/Zonemaster/Backend/DB/MySQL.pm
lib/Zonemaster/Backend/DB/PostgreSQL.pm
lib/Zonemaster/Backend/DB/SQLite.pm
script/create_db_mysql.pl
script/create_db_postgresql_9.3.pl
script/zonemaster_backend_rpcapi.psgi
share/backend_config.ini
share/create_db_sqlite.pl
share/patch_mysql_db_zonemaster_backend_ver_1.0.3.pl
share/patch_mysql_db_zonemaster_backend_ver_5.0.0.pl
share/patch_mysql_db_zonemaster_backend_ver_5.0.2.pl
share/patch_postgresql_db_zonemaster_backend_ver_1.0.3.pl
share/patch_postgresql_db_zonemaster_backend_ver_5.0.0.pl
share/travis_mysql_backend_config.ini
share/travis_postgresql_backend_config.ini
share/travis_sqlite_backend_config.ini
share/zm-rpcapi.lsb
share/zm-testagent.lsb
share/zm_rpcapi-bsd
share/zm_testagent-bsd

This PR is about having separate a separate config section for each db engine.
Fixes #719.
As @matsduf pointed out, PR #717 must be merged before this is merged or else there is a risk of filling up the log files.
Config format:
* New sections are added. The new section names are upper-case-only for consistency with previous sections.
* The old properties are deprecated.
Implementation:
* New accessor methods for the properties are added to Config.pm. They're named after the config section and property name, with an underscore in between. There is some precedence for this naming scheme in Config.pm.
* If the new properties are absent in the config file, the old ones are used as fallbacks to make sure old config files keep working.
* The accessors for the old properties are removed.
* The …

Separate config section for each db engine

---

lib/Zonemaster/Backend/RPCAPI.pm
t/test01.t

In #731 when using SQLite, the code suggests that the database file should be deleted if it was created for the tests. I forgot to update the path to the database file. This fixes that.
In #734 , I discover some old code, I decided to not touch it at that time as `test01.t` was using it. This removes this old code and updates `test01.t` accordingly.
There are calls to `test_progress` and to `get_data_from_parent_zone` using the `SCALAR` parameter in [`CodeSnippets/client.pl` (v6.1.0)](https://github.com/zonemaster/zonemaster-backend/blob/v6.1.0/CodeSnippets/client.pl). I'm not sure how up to date this snippet is, so I haven't updated it yet. I totally can if you think it is worth it.

Cleaning and fixing in the continuity of #731 and #734

---

.travis.yml
Makefile.PL
docs/Installation.md
lib/Zonemaster/Backend/Config.pm
lib/Zonemaster/Backend/RPCAPI.pm
share/travis_postgresql_backend_config.ini
t/config.t

This PR adds Zonemaster::Backend::Config->parse(). This method makes unit testing more predictable by letting unit tests embed their configuration(s) instead of having Zonemaster::Backend::Config figure out which file to open and read and risking to use another configuration than the one the developer intended.
An illustration of how such unit tests can be written is provided in t/config.t.
This PR is made as a first step towards #685, but it also provides a way to update other unit tests to make them more predictable.
Zonemaster::Backend::Config:
* Z::B::Config->parse() is broken out from Z::B::Config->load_config().
* Existing validations are moved out from accessor methods and into parse().
* Some drive-by clean-up of the Z::B::Config code.
* A seconds-to-minutes conversion is moved …

Parse config

---

docs/Configuration.md
lib/Zonemaster/Backend/Config.pm
t/config.t
t/test_validate_syntax.t

This PR lays some groundwork for #685.
It also fixes a warning that was noted by @pnax in https://github.com/zonemaster/zonemaster-backend/pull/745#pullrequestreview-638608629.
* No behavioral changes with regard to validation.
* No documentation changes to property getters.
* No code changes with regard to complex properties.
* New property getters are introduced, but the old ones are kept in place. Call sites aren't updated to use the new ones either. At first I wanted to include this cleanup in the PR, but the surface area was large enough that I'm leaving that for a follow-up PR.
Format specification:
* Some details are included that were previously only documented in the POD of the getter methods.
* Simple properties undergo minor editing to make them more structurally similar to …

Uniform config property getter methods

---

docs/Configuration.md

Add documentation to the last two keys. I am not completely satisfied but this is the best I came up with to explain how we use these values in the code.
There was also a discussion on deprecating these keys in #623, this will come in another PR.

Document keys number_of_processes_for_{frontend,batch}_testing

---

docs/Configuration.md
lib/Zonemaster/Backend/Config.pm
lib/Zonemaster/Backend/DB.pm
lib/Zonemaster/Backend/DB/MySQL.pm
lib/Zonemaster/Backend/DB/PostgreSQL.pm
lib/Zonemaster/Backend/DB/SQLite.pm
lib/Zonemaster/Backend/RPCAPI.pm
lib/Zonemaster/Backend/TestAgent.pm
script/create_db_mysql.pl
script/create_db_postgresql_9.3.pl
script/zonemaster_backend_testagent
share/create_db_sqlite.pl
share/patch_mysql_db_zonemaster_backend_ver_1.0.3.pl
share/patch_mysql_db_zonemaster_backend_ver_5.0.0.pl
share/patch_mysql_db_zonemaster_backend_ver_5.0.2.pl
share/patch_postgresql_db_zonemaster_backend_ver_1.0.3.pl
share/patch_postgresql_db_zonemaster_backend_ver_5.0.0.pl
t/config.t

This PR is a follow-up to #749.
Included:
* Cleaning up after #749.
* Documentation is added for the new getters from #749.
* Documentation for the database connection related properties is updated for consistency.
* Relevant pieces of cleaned up documentation is integrated into the backend config format specification.
* SQL-queries adjacent to uses of the new property getters are refactored to use the ?-syntax instead of string concatenation. To facilitate a few other refactorings are also included.
Excluded:
* Functional changes.
Security:
* In a couple of places another layer of security is added by using SQL-injection resistant ? syntax. This also makes the code easier to review with regard to security.
Documentation:
* The backend config format specification gets a tiny improvement …

Use uniform accessors

---

docs/Configuration.md
lib/Zonemaster/Backend/DB/MySQL.pm
lib/Zonemaster/Backend/DB/PostgreSQL.pm
lib/Zonemaster/Backend/DB/SQLite.pm
lib/Zonemaster/Backend/RPCAPI.pm

This PR is a follow-up to https://github.com/zonemaster/zonemaster-backend/pull/692#discussion_r551941117.
The ZONEMASTER.age_reuse_previous_test property is specified in seconds, but it was rounded to whole minutes.
This PR removes rounding logic and relieves us from having to describe this normalization in the configuration documentation.
1. Set `ZONEMASTER.age_reuse_previous_test` to 30 in your backend config file.
2. (Re)start your RPCAPI daemon to make sure the configuration is in effect.
3. Run:
```sh
zmtest null.example >/dev/null
sleep 15
zmtest null.example >/dev/null
sleep 30
zmtest null.example >/dev/null
```
4. Before the fix: All three runs result int the same testid.
After the fix: The first two runs result in the same testid, but the third one results in a different one.

Stop rounding test shelflife to whole minutes

---

t/config.t
t/test01.t

This PR fixes a problem when installing the dist tarball where test01.t would require that /var/lib/zonemaster/ exists.
Fixes #762.
Basically this PR does two things.
1. It makes test01.t independent of the default config file, and
2. It adds a test to config.t to make sure the default config file is valid.
Instead of creating its SQLite database file under /var/lib/zonemaster it creates a temporary directory for the database file. (The temporary directory is automatically cleaned up.)
Make sure test suite passes when executed by cpanm:
```sh
make dist
sudo rm -rf /var/lib/zonemaster
cpanm --test-only Zonemaster-Backend-*.tar.gz
```

Fix broken installation

---

docs/Installation.md

Installation must work with both csh and sh.

Makes SQLite installation shell independent on FreeBSD

---

share/zm-rpcapi.lsb
share/zm-testagent.lsb

This PR makes systemd aware of failures during daemon startup. In particular it makes `systemctl {start,status} {zm-rpcapi,zm-testagent}` actually report failures.
Without this the config validation feature is pretty lame.
The LSB service scripts are updated to exit with an error status if any of their commands fail.
I have NOT tested how FreeBSD behaves in this respect. I suggest that is handled separately from this PR.
Make sure the daemons are stopped and that the config is invalid:
```
sudo systemctl stop zm-rpcapi
sudo systemctl stop zm-testagent
sudo sed -i '/\bengine\b/ s/=.*/= Excel/' /etc/zonemaster/backend_config.ini
```
Verify that you get an error message when you starting `zm-rpcapi` and that systemctl knows that it failed:
```
sudo systemctl start zm-rpcapi
sudo systemctl …
```

Tell OS about failed daemon startup (Linux)

---

lib/Zonemaster/Backend/DB.pm

Fix a crash.
Introduced in #759.
Fixes #778.
This PR updates a forgotten call site after renaming a method.
(I have not yet tried to reproduce the bug using this procedure, but from my current understanding it should work.)
1. Set ZONEMASTER.max_zonemaster_execution_time to something low.
2. Restart zm-testagent.
3. Start a new test (A).
4. Kill the test's worker process before it can finish.
5. Wait for the test to expire.
6. Verify that zm-testagent is still alive by starting a new test and seeing that it's being processed.

Update call site after method name change

---

lib/Zonemaster/Backend/Validator.pm
t/validator.t

Make zm-rpcapi accept fake delegation again.
Introduced in #759.
Fixes #779.
This PR removes stray backslashes from regexes.
It also adds regression tests for the affected validation primitives.
Start a new test with fake delegation that includes an IP address and verify that you don't get a validation error:
```
zmb start_domain_test --domain example.com --nameserver a.example.com:192.0.2.1
zmb start_domain_test --domain example.com --ds-info keytag=0,algorithm=0,digtype=0,digest=1234567890123456789012345678901234567890
```

Make zm-rpcapi accept fake delegation again

---

docs/Installation.md

Github makes it easy to copy the entire content in so called fenced code block (e.g. with backticks). This PR splits one such code block because you will never want to paste all lines to a server that you install.

Make it easier to copy from installation document on Github

---

script/zmb

set ip param to empty string if undefined, fix #780 
```
% ./script/zmb --verbose start_domain_test --nameserver ns.nic.se --domain iis.se
{"params":{"nameservers":[{"ip":"","ns":"ns.nic.se"}],"domain":"iis.se"},"method":"start_domain_test","jsonrpc":"2.0","id":1}
{"id":1,"result":"e3d836d48136428f","jsonrpc":"2.0"}
```
```
% ./script/zmb --verbose start_domain_test --nameserver ns.nic.se:91.226.36.45 --domain iis.se
{"id":1,"params":{"domain":"iis.se","nameservers":[{"ns":"ns.nic.se","ip":"91.226.36.45"}]},"jsonrpc":"2.0","method":"start_domain_test"}
{"id":1,"result":"dc93b829f18d2d64","jsonrpc":"2.0"}
```

Fix handling of nameserver option in zmb

---

LICENSE

In the copyright statement a range of years is given. That requires updates, but year is not needed.
Nothing is said about copyright for contributors.
Removes year from copyright and give the correct "translation" of Internetstiftelsen. Adds statement about contributor's copyright.
No need to test.

Updates license statements (zonemaster-backend)

---

lib/Zonemaster/Backend/Config.pm

Document why the normalized database engine name is in a specific camel case form in Config.pm
One line (comment) in the Perl module.
It does not change the code.

Adds documentation of camel case database engine name

---

script/zmb
script/zmtest

Add another RPC API method to zmb.
N/A
Add `zmb get_test_params`.
Rename the `--testid` parameter to `--test-id` for the `test_progress` and `get_test_results` commands. The old parameter name still works but emits a deprecation warning.
Start a test and verify that the output from `get_test_params` looks reasonable:
```sh
testid="$(zmb start_domain_test --domain example | jq -r .result)"
zmb get_test_params --test-id "$testid" | jq .
```
Verify that zmtest still works:
```sh
zmtest example.com
```

Implement zmb get_test_params

---

docs/Configuration.md
lib/Zonemaster/Backend/Config.pm
lib/Zonemaster/Backend/DB/MySQL.pm
lib/Zonemaster/Backend/DB/PostgreSQL.pm
t/config.t

Adds a new configuration key to specify the database port for MySQL and PostgreSQL as suggested in #496.
~This PR needs #753 to be merged first, and then rebased on top of develop.~
This adds 2 new configuration entries, one in the MYSQL section and the other in the POSTGRESQL section. Each entry makes it possible to specify the port number on which the database server is listening. If the `host` key is not present, then the behavior is the same as before, each DBI uses its default port value.
With MySQL, if you want to talk with the database server on the local machine with another port number, you need to define the loopback IP address in the MYSQL.host (otherwise using `localhost` will result in using a UNIX socket as explained in the [DBD::mysql …

Configuration of the database port

---

docs/API.md
docs/Configuration.md

Today the `LANGUAGE section` documentation is quite long and if you're looking for something specific you may end up having to read all of it. This PR breaks it down into shorter sub-headings with clear titles.
I originally made these changes a good while ago, but I didn't get around to actually make a PR out of them until now.
This PR moves around sections of text and inserts new headings, but it doesn't change any of the original words.
A list from the LANGUAGE.locale is integrated in to another one under `get_language_tags`.
Some text from LANGUAGE.locale and some from `get_language_tags` is integrated into the definition of the language tag data type definition.
This PR does not need testing as it only affects documentation.

Make LANGUAGE section docs easier to navigate

---

docs/API.md
docs/Configuration.md
lib/Zonemaster/Backend/Config.pm

Language tags have been defined to possibly include country code, but there is no real use case for that, and it only adds to the complexity of documentation and code.
The possibility to have an empty LANGUAGE.locale unnecessarily adds to complexity.
Resolves issue #794 and deprecates the use of empty LANGUAGE.locale.
* Deprecates language tags with country code in API.pm
* Deprecates empty LANGUAGE.locale and clarifies in Configuration.pm
* Adds warning in Config.pm if LANGUAGE.locale is empty.
If LANGUAGE.locale is empty, a log messages will be outputted to the log file. If non-empty, there should be no change in behavior. There should be no change besides the log message.

Deprecate country code

---

docs/Configuration.md
lib/Zonemaster/Backend/Config.pm
lib/Zonemaster/Backend/RPCAPI.pm
lib/Zonemaster/Backend/Validator.pm
t/config.t
t/validator.t

This PR refactors the implementation of LANGUAGE.locale.
This PR extends the use of patterns for API and validation introduced in #759 and #757 to also cover the LANGUAGE.locale property.
These changes were developed in parallel with #759 and #757 as part of resolving #685. These changes are not part for solving in a technical sense, because the validations were already there. But they are in an architectural sense because they make the Config module interface more cohesive. These changes also played an important role when designing the new Config module interface, its internal structure and the new validation framework.
The methods Language_Locale_hash() and ListLanguageTags() are replaced by the LANGUAGE_locale() getter.
Call sites are updated to use the new getter instead.
The internal …

Refactor locale validation

---

lib/Zonemaster/Backend/Config.pm
lib/Zonemaster/Backend/RPCAPI.pm
lib/Zonemaster/Backend/TestAgent.pm
script/zonemaster_backend_testagent

This PR is mainly a refactoring in preparation for implementing the validation of the PUBLIC PROFILES and PRIVATE PROFILES sections, but it also includes some improvements to error handling.
This PR is a step towards #685.
When zm-testagent fails to start, the error is written to the log file.
A weird behavior is fixed. Normally when you specify a non-existing path for a profile, zm-testagent refuses to start. But if the name of the profile is "default", zm-testagent starts anyway and the default profile is used instead of the non-existent one. After this PR zm-testagent will refuse to start if a profile path does not exist - no matter what name the profile has.
Error messages from two sources are updated with more context. In one case the path of the offending profile file is included, …

Refactorings in preparation for validation of profile config properties

---

lib/Zonemaster/Backend/Config.pm
lib/Zonemaster/Backend/DB.pm
lib/Zonemaster/Backend/DB/MySQL.pm
lib/Zonemaster/Backend/DB/PostgreSQL.pm
lib/Zonemaster/Backend/DB/SQLite.pm
lib/Zonemaster/Backend/RPCAPI.pm
lib/Zonemaster/Backend/TestAgent.pm
script/create_db_mysql.pl
script/create_db_postgresql_9.3.pl
script/zonemaster_backend_testagent
share/create_db_sqlite.pl
share/patch_mysql_db_zonemaster_backend_ver_1.0.3.pl
share/patch_mysql_db_zonemaster_backend_ver_5.0.0.pl
share/patch_mysql_db_zonemaster_backend_ver_5.0.2.pl
share/patch_postgresql_db_zonemaster_backend_ver_1.0.3.pl
share/patch_postgresql_db_zonemaster_backend_ver_5.0.0.pl
t/test_validate_syntax.t

This PR updates the database connection code so that it's possible to get a database adapter instance that doesn't correspond to the contents of a configuration file. This is useful if you want to include database schema definition in the database adapter code.
This is mostly about refactoring, but it also includes fixing of a bug (introduced since last release) and some minor improvements.
This PR is a step towards both #805 and #806.
* Fixes connecting to MySQL over IPv6.
* Fixes the syntax of the data source name for PostgreSQL. I'm not sure why the old syntax used to work or why it doesn't anymore (on CentOS 8), but this PR changes the syntax to the one specified in [DBD::Pg::connect](https://metacpan.org/pod/DBD::Pg#connect).
* The database adapter constructor interfaces are changed …

Update database connection code

---

MANIFEST
docs/API.md
lib/Zonemaster/Backend/DB.pm
lib/Zonemaster/Backend/DB/MySQL.pm
lib/Zonemaster/Backend/DB/PostgreSQL.pm
lib/Zonemaster/Backend/DB/SQLite.pm
lib/Zonemaster/Backend/RPCAPI.pm
t/db.t
t/test01.t

When we store a test in the database, we also store a fingerprint based on some criteria, that can be used to avoid running the same time in a short period of time.
This PR harmonizes the way we compute the fingerprint so that we can reuse tests that are similar, even if some properties are left out by the client.
This also normalize the value stored in the `params` database field.
As explained in #775, depending on the client used, some properties are used in the computation of the fingerprint or not. This PR solves this by always using the same properties (falling back to a default value if the property is not set).
Fixes #775
* a first commit is only about removing trailing spaces and changing tabs into spaces (839f435)
* update variable name "deterministic hash" into "fingerprint"
* …

Properly define properties to use for database fingerprint (deterministic hash)

---

script/zmb

For RPCAPI method get_test_history zmb has a non-supported parameter "nameservers" and a missing parameter "filter". This PR corrects that.
This PR also clarifies a cryptic error message.
Before this PR from `zmb man`:
```
get_test_history
zmb [GLOBAL OPTIONS] get_test_history [OPTIONS]
Options:
--domain DOMAIN_NAME
--nameserver true|false|null
--offset COUNT
--limit COUNT
```
Before this PR:
```
{
"id": 1,
"method": "get_test_history",
"params": {
"frontend_params": {
"nameservers": true,
"domain": "xb"
}
}
}
{
"id": 1,
"error": {
"message": "Invalid method parameter(s).",
"code": "-32602",
"data": "/frontend_params: Properties not allowed: nameservers."
},
"jsonrpc": "2.0"
}
```
Issue #812 is related to this issue.
This PR removes the incorrect parameter and implements …

Corrects zmb

---

lib/Zonemaster/Backend/RPCAPI.pm
lib/Zonemaster/Backend/Translator.pm

This PR fixes a problem where translations don't work unless you have more locales installed than the ones prescribed in the installation instruction.
Fixes #809.
This PR corrects the usage of Zonemaster::Engine::Translator->locale().
Make sure that your LANGUAGE.locale contains da_DK:
```sh
cat /etc/zonemaster/backend_config.ini
```
Make sure that the only locale listed for Danish is `da_DK.utf8`:
```sh
locale -a
```
Restart you daemons:
```sh
sudo systemctl restart zm-rpcapi zm-testagent
```
Acquire a test id:
```sh
zmtest zonemaster.net
```
Verify that you can get the results in Danish (make sure to set $TESTID or replace it with a test id that exists in the database):
```sh
zmb get_test_results --lang da --test-id $TESTID | jq -S .result.results[0]
```

Fix translation

---

docs/Configuration.md
lib/Zonemaster/Backend/Config.pm
lib/Zonemaster/Backend/RPCAPI.pm
lib/Zonemaster/Backend/TestAgent.pm
lib/Zonemaster/Backend/Validator.pm
t/config.t
t/validator.t

This PR mainly does two things:
* It implements the validation rules already described the PUBLIC PROFILES and PRIVATE PROFILES sections.
* It fixes a bug that prevented the use of profiles in the PRIVATE PROFILES section. (#808)
This PR currently contains all the commits from #802. After that PR is merged this one will be rebased onto the develop branch.
This is the last leg of #685.
Fixes #808.
This PR contains lots of tiny changes that update the same parts of the code. To understand the changes I recommend going through the changes commit by commit. When adding review comments, keep in mind that lines changed in an earlier commit may well be updated in a later commit.
* It adds getters for the validation of the PUBLIC PROFILES and PRIVATE PROFILES sections.
* It simplifies the …

Validate profiles

---

docs/API.md
docs/Configuration.md

Clarifies the limitations on profiles in the configuration and updates the documentation in the API documentation.
Documentation only, no change of implementation.

Clarifies profiles in the documentation

---

docs/API.md

The API document says that the reuse time is hard coded, which it is not. It also gives  an incorrect description of what parameters that are taken into account when comparing two requests.
Description is corrected.
This PR only updates a document, not the implementation.

Corrects the description of the reuse time

---

script/zmb

zmb is an CLI interface against the RPCAPI. Methods `add_batch_job` and `get_batch_job_result` are missing.
Resolves part of #628.
Methods `add_batch_job` and `get_batch_job_result` are added.
* Find details on options with `zmb man` and the API documentation.
* Create a user and password with existing method in zmb (`zmb add_api_user`).
* Create a simple batch with no extra options with `zmb add_batch_job`. Take note of the batch-ID ("result").
* Get the result with (`zmb get_batch_job_result`).
* All tests must be completed in the batch before next step.
* Create a new batch with name server and DS options.

Adds API methods add_batch_job and get_batch_job_result

---

docs/API.md
docs/Configuration.md
lib/Zonemaster/Backend/Config.pm
lib/Zonemaster/Backend/RPCAPI.pm
lib/Zonemaster/Backend/Validator.pm
script/zonemaster_backend_rpcapi.psgi
share/backend_config.ini
t/test01.t
t/test_validate_syntax.t
t/validator.t

This PR changes how error related to param validation are return to the client to allow better analysis client side. It also prevent the internal error due to failed validation.
Replaces #795.
Addresses #703, is a requirement for https://github.com/zonemaster/zonemaster-gui/issues/177 and https://github.com/zonemaster/zonemaster-gui/issues/178. Dependency for  #230.
* The json validation error are split in an array of object to allow better parsing client side (thus enabling better error message on the GUI). The json validation error are mapped to a set of custom defined messages to allow more user friendly messages but also translation.
`curl -sH "Content-Type: application/json" --data '{"method":"start_domain_test","params":{"nameservers":[{"ns":"/!\\", "ip":":::1"}], …

Return an array of error for request validation

---

.travis.yml
lib/Zonemaster/Backend/Config.pm

Improve the config search mechanism 
Following the comment https://github.com/zonemaster/zonemaster-backend/pull/833#issuecomment-888965227
* iterate through a default config location list to find an existing file
* add default freebsd location to the search list (`/usr/local/etc/zonemaster/backend_config.ini`)
* update travis file to correctly install the share directory
* Create the file `/etc/zonemaster/backend_config.ini`, run the backend, check that this is the config file loaded, then delete it
* Create the file `/usr/local/etc/zonemaster/backend_config.ini`, run the backend, check that this is the config file loaded, then delete it
* Create the file `/tmp/my_config.ini`, set the environment variable `ZONEMASTER_BACKEND_CONFIG_FILE` to `/tmp/my_config.ini`, run the backend, check …

improve config search and add default freebsd config location

---

lib/Zonemaster/Backend/RPCAPI.pm

Fix add_api_user method on dual stack computer when querying 127.0.0.1.
Add the mapped address `::ffff:127.0.0.1` to the list of authorized remotes.
executing `zmb -s http://127.0.0.1:5000 add_api_user --username toto --api-key secret` on a dual stack computer should work and return 1 as result.

allow ipv4 mapped addresses

---

lib/Zonemaster/Backend/RPCAPI.pm
script/zonemaster_backend_rpcapi.psgi
script/zonemaster_backend_testagent

Get better log files.
Use logger instead of warn.
```
./script/zmb get_test_results --test-id 123456789abcdef0 --lang fr
```
This trigger an exception (it should not but that for another PR), check that the message is correctly formatted:
```
2021-08-11T10:31:23Z [63992] ERROR - Internal error 012: Unexpected error in the get_test_results API call: [malformed JSON string, neither array, object, number, string or atom, at character offset 0 (before "(end of string)") at /home/gbm/workspace/zonemaster/zonemaster-backend/lib/Zonemaster/Backend/DB/PostgreSQL.pm line 235.]
```

use logger instead of warn

---

lib/Zonemaster/Backend/DB.pm
lib/Zonemaster/Backend/DB/MySQL.pm
lib/Zonemaster/Backend/DB/PostgreSQL.pm
lib/Zonemaster/Backend/DB/SQLite.pm
script/zonemaster_backend_testagent

Terminate dead tests as soon as they die to not have the user to wait `max_zonemaster_execution_time` to see the error.
* Add a few new methods in DB
* `process_dead_test` terminate the test or schedule retry
* `force_end_test` mark the test as failed, method reused in `process_unfinished_tests`
* `get_timestamp` return the number of second since the test started
* When a test dies, process the termination of the test right away by calling `process_dead_test`
Test a domain that causes a failure, the test results should show up as soon as the test dies.
```
time ./script/zmtest kamglass.com.pl
```

process dead tests quickly

---

docs/API.md
lib/Zonemaster/Backend/DB.pm
lib/Zonemaster/Backend/DB/MySQL.pm
t/db.t

This PR removes the use of `queue` and `priority` in the fingerprint computation.
Fixes #815 
Revert the use of `priority` and `queue` to compute the fingerprint added in #798.
**Remark**: this value is still kept in the JSON string stored into the `params` column.
1. create a test using `add_batch_job`:
```
BATCHID=$(zmb add_batch_job --username zmb --api-key zmb --domain example.com | jq -r .result)
```
2. create a test using `start_domain_test` for the same domain:
```
TESTID=$(zmb start_domain_test --domain example.com | jq -r .result)
```
3. wait for the batch job to finish:
```
zmb get_batch_job_result --batch-id $BATCHID
```
4. check that `$TESTID` is the same as the id in the batch job
```
diff <(echo $TESTID) <(zmb get_batch_job_result --batch-id $BATCHID | jq -r …
```

Remove "priority" and "queue" parameters from fingerprint computation

---

MANIFEST
README.md
docs/upgrade_db_zonemaster_backend_ver_7.0.0.md
share/patch_mysql_db_zonemaster_backend_ver_7.0.0.pl
share/patch_postgresql_db_zonemaster_backend_ver_7.0.0.pl
share/patch_sqlite_db_zonemaster_backend_ver_7.0.0.pl

Update the old 'undelegated' values in the database.
Fixes #829
Add patch scripts.
* Check the value of delegated vs undelegated tests (all test are delegated, so the second query should return nothing except if you have the patch for undelegated tests in which case there can be a few).
```pgsql
select DISTINCT params->>'ds_info' as ds_info, params->>'nameservers'  as nameservers from test_results where undelegated = 0 ;
select DISTINCT params->>'ds_info' as ds_info, params->>'nameservers' as nameservers from test_results where undelegated = 1 ;
```
* Apply update script `perl zonemaster-backend/share/patch_postgresql_db_zonemaster_backend_ver_7.0.0.pl` (ignore error if the table has already been changed, "if not exists" is not compatible with PG 9.3)
* Repeat the first step to verify …

add scripts to backfill undelegated fields in db

---

docs/Installation.md
share/backend_config.ini

Try to remove some overhead in the installation process by moving the parts on installing MariaDB/MySQL and PostgreSQL engines to the end of the document.
N/A
* Remove the Ubuntu section, merge it with the Debian section
* Update the "doc/Installation.md" with a new "Appendices" section.
* Move all references to MariaDB/MySQL or PostgreSQL to the appendices.
* Move the cleaning instructions to an appendix.
* Update the `backend_config.ini` file to use SQLite database engine by default
N/A (documentation only).

Update documentation to use SQLite by default

---

lib/Zonemaster/Backend/DB/SQLite.pm

This PR creates indexes for the `test_results` table with SQLite.
This is part 1/11 from #841
Create indexes in SQLite.
A newly created SQLite database should have indexes `PRAGMA index_info(test_results)`.
Upgrading a database will be done in a later PR.

Missing index with SQLite

---

docs/API.md

Change to link from http to https because it is possible.
The only updates a link in `API.md`.
Verify that the link to the JSON-RPC specification is correct.

Change link from http to https

---

Makefile.PL
docs/Configuration.md
docs/Installation.md
docs/upgrade_db_zonemaster_backend_ver_7.0.0.md
lib/Zonemaster/Backend/Config.pm
lib/Zonemaster/Backend/Validator.pm
script/zonemaster_backend_rpcapi.psgi
share/backend_config.ini

Secure the add_api_user method.
Fixes #838 
* Use `Plack::Middleware::ReverseProxy`  to set the environment according to the proxy headers
* Add two configuration keys `API.enable_add_batch_job` and `API.enable_add_api_user` to enable the corresponding api methods (disabled by default).
* Running `./script/zmb add_api_user --username toto --api-key secret` should return the error `"Procedure 'add_api_user' not found"`.
* Running `./script/zmb add_batch_job --domain example.com --username toto --api-key secret` should return the error `"Procedure 'add_batch_job' not found"`.
* Enable the add_api_user method.
* run the API behind a reverse proxy on the same host
```
curl -s "Content-Type: application/json" --data '{"method":"add_api_user","params":{"username":"toto","api_key":"toto"},"id":1, …
```

use plack reverse proxy middleware to get real remote ip

---

docs/API.md
lib/Zonemaster/Backend/DB/MySQL.pm
lib/Zonemaster/Backend/DB/PostgreSQL.pm
lib/Zonemaster/Backend/DB/SQLite.pm
lib/Zonemaster/Backend/RPCAPI.pm

Add more information on the tests in history.
#830
Return an `undelegated` in the test history items.
Create a delegated and undelegated test, then query the history and check the `undelegated` property:    
`./script/zmb get_test_history --domain toto.com --filter all | jq`
```json
{
"result": [
{
"creation_time": "2021-08-04 08:13:16",
"id": "9aa193588f53b8d8",
"overall_result": "error",
"undelegated": 1
},
{
"id": "b60fb8f881b199f8",
"creation_time": "2021-07-20 08:39:01",
"undelegated": 0,
"overall_result": "error"
}
],
"id": 1
}
```

add undelegated value in results history

---

lib/Zonemaster/Backend/DB.pm
lib/Zonemaster/Backend/DB/MySQL.pm
lib/Zonemaster/Backend/DB/PostgreSQL.pm
lib/Zonemaster/Backend/DB/SQLite.pm
script/zonemaster_backend_testagent

fix shared db handler

---

lib/Zonemaster/Backend/DB.pm
lib/Zonemaster/Backend/DB/MySQL.pm
lib/Zonemaster/Backend/DB/PostgreSQL.pm
lib/Zonemaster/Backend/DB/SQLite.pm
share/patch_mysql_db_zonemaster_backend_ver_7.0.0.pl
share/patch_postgresql_db_zonemaster_backend_ver_7.0.0.pl
share/patch_sqlite_db_zonemaster_backend_ver_7.0.0.pl
t/test01.t

This PR tries to improve and add consistency between database engines. There are PRs to update the database in a way that breaks things (new `undelegated` column in PosgreSQL for instance). It might be nice to take the opportunity of this new Backend release to improve and fix some behaviors in the databases.
A first part in this PR is to improve the `create_db()` routine in order to be able to call it at daemon startup (which will be handle in another PR #846 ).
Based on top of #833 and #834
Addresses #832, #840
There are several changes. This PR can easily be split in smaller PRs.
* (1/11) Create indexes in SQLite -> #865
* (2/11) Always check that a table, index or trigger does not exists before creation. For some cases, the clause `IF NOT EXISTS` is sufficient, for others, we need …

Harmonize databases

---

docs/API.md
docs/Configuration.md

This PR documents that affect on the API by the new keys for batch methods added by #850 and #839.
* Adds missing entries in table of contents (`docs/Configuration.md`)
* Several updates to `docs/API.md`:
* Updates link text for IPv6 address format.
* Updates specification "add_api_user" method and "add_batch_job" method, respectively.
* Adds reference to "enable_add_api_user" and "enable_add_batch_job" configuration keys.
* Adds examples of error messages for both methods.
* Adds new links in link section.
* Sorts links in link section.
This PR resolves #864.
Two documents are updated:
* docs/Configuration.md
* docs/API.md
Documentation only. Verify the claims in the documents.

Adds missing information in API document

---

MANIFEST

This PR resolves an issue when creating distribution package:
```
$ make distcheck
"/usr/local/bin/perl" "-Iinc" "-MExtUtils::Manifest=fullcheck" -e fullcheck
Not in MANIFEST: docs/Upgrade.md
```
The file `docs/Upgrade.md` was added in PR #879 but MANIFEST was not properly updated.
Only MANIFEST is updated.
Make sure that `make distcheck` gives a clean output.

Adds missing file to MANIFEST

---

lib/Zonemaster/Backend/DB/MySQL.pm
lib/Zonemaster/Backend/DB/PostgreSQL.pm
lib/Zonemaster/Backend/DB/SQLite.pm
share/patch/patch_mysql_db_zonemaster_backend_ver_8.0.0.pl
share/patch/patch_postgresql_db_zonemaster_backend_ver_8.0.0.pl
share/patch/patch_sqlite_db_zonemaster_backend_ver_8.0.0.pl

Remove the `nb_retries` column from the database.
Second step of  #881.
* Updates the database creation scripts
* Update the patch scripts to remove the column
* Run the patch scripts on a existing database with the `nb_retries` column (some error messages can be ignored if the database was already partially migrated)
* Create new databases

remove the retry column in db

---

.travis.yml

The oldest perl version that we support is 5.26, don't run tests on unsupported perl versions.
Remove version 5.24, 5.22 and 5.16 from tests
...

remove unsupported perl version from travis

---

docs/Installation.md
share/cleanup-mysql.sql

Do not fail on cleanup.
Fixes #887 
Update `cleanup-mysql.sql`.
Follow the instructions to install the MySQL database and then run the cleanup command. No errors should be emitted.

Fix MySQL cleanup

---

MANIFEST

More MO files were indirectly added by PR #898 but it was not specified in the MANIFEST.
`make distcheck` should not complain about unknown MO files, and the MO files should be included in the distribution file.

Add MO files to manifest

---

docs/Upgrade.md
docs/upgrade/upgrade_zonemaster_backend_ver_8.0.0.md

Some old files are not cleaned when following the upgrade instructions.
Instead of manually listing and removing each deprecated files, `cpanm --uninstall` will do the cleaning for us.
Follow #907
Instructions to run `cpanm --uninstall Zonemaster::Backend` when upgrading the module.
Install the previous version of Backend and follow the instructions from the "Clean old file section" of the upgrade document.

Clean old files when upgrading

---

share/fi.po

Adds translation into Finnish provided by @samisalmensuo. Error message translation has been added by #891.
Resolves #911
Updates `share/fi.po`
Error messages should be in Finnish if Finnish has been selected.

Adds Finnish translation of error messages

---

lib/Zonemaster/Backend/DB.pm

The different database drivers do not retrieve the data with the same Perl's internal representation. Therefore it is required to check this representation before calling "decode_json" that "expects an UTF-8 (binary) string" (https://metacpan.org/pod/JSON::PP#decode_json).
Fixes #931
Also see #570
Fix the `get_test_params` method in `DB.pm`.
Check that internationalized and non-internationalized domains works properly for all database engines.

Fix internationalized testing failure with error: "malformed UTF-8 character in JSON string"

---

lib/Zonemaster/Backend/DB/SQLite.pm

Fix inconsistency in SQLite test's age.
#841 did not update SQLite to use `creation_time` instead of `test_start_time` when looking for test to reuse, which is inconsistent with MySQL and PostgreSQL.
In fact #841 made the change (a8a4cee) and removed it in a later commit (5df15c0).
Addresses #840.
Update method `recent_test_hash_id` in `DB/SQLite.pm`.
With SQLite configured, start two tests for the same domain. Before, this fix, the test ID is different. With this fix, the test ID should be the same (until `age_reuse_previous_test` seconds are passed).
```
curl -sH "Content-Type: application/json" --data '{"method":"start_domain_test","params":{"domain":"domain.example"},"id":1,"jsonrpc":"2.0"}' localhost:5000/api | jq
```

Fix inconsistency in SQLite test's age

---

docs/Installation.md

* Updates the instruction for PostgreSQL for FreeBSD to resolve conflict.
* Removes `-y` option to FreeBSD `pkg` to prevent installation conflicts to just pass by.
Resolves #925.
Follow the instruction for PostgreSQL for FreeBSD.

Updated instruction for FreeBSD due to updated indirect dependencies

---

script/zonemaster_backend_testagent

The pre-flight checks were always run when calling `zonemaster_backend_testagent` daemon. If they fail the daemon stops without performing its task. Therefore the daemon cannot be properly stopped if the checks fail. This runs the checks only on daemon `start`.
Fixes #905
Add a check before running pre-flight checks to run them only when calling the agent with the `start` parameter and bypass them for any other parameters.
see #905 description

Fix unstoppable Testagent daemon

---

.travis.yml

An update in travis-perl added comment to the init file. This makes the `eval` call fail because the script become a one-liner in this case with a comment in the middle.
This PR is about removing commented lines from the script before running it.
https://github.com/travis-perl/travis-perl.github.io/commit/34d18cc150497a00dc7719fea2472c183e6607ad
Credits to @blacksponge

Fix travis-perl error

---

script/zmb

Make it easy to test the `zmb start_domain_test --language` option.
This simplified the v2021.2 release testing.
Adds a new option to `zmb start_domain_test`.
Run this command and see that the error messages come back in Swedish:
```sh
zmb start_domain_test --domain =bogus= --language sv | jq -S
```
```json
{
"error": {
"code": "-32602",
"data": [
{
"message": "Domännamnstecken stöds inte",
"path": "/domain"
}
],
"message": "Ogiltig metodparameter."
},
"id": 1,
"jsonrpc": "2.0"
}
```

Add support for language param in start_domain_test

---

lib/Zonemaster/Backend/DB/MySQL.pm
lib/Zonemaster/Backend/DB/PostgreSQL.pm
lib/Zonemaster/Backend/DB/SQLite.pm

Harmonize the code for `get_test_history` across database engines and fixes #888.
Fixes #888 
* refactoring
* use SQL bind parameters
* remove unused `params` value
* keep finished tests only 
see #888 description and example

Improve get_test_history

---

MANIFEST
MANIFEST.SKIP
lib/Zonemaster/Backend/Config.pm
t/00-load.t

This is mainly a code quality improvement. It also avoids locating the default backend_config.ini if it isn't needed.
N/A
* It avoids executing some code at load time.
* It replaces a global variable (`$Zonemaster::Backend::Config::path`) with a procedure (`Zonemaster::Backend::Config::get_default_path()`).
* It adds code documentation about where the default backend_config.ini file is sought.
* It simplifies the code to determine the config file path.
This should not change the behavior of Backend in production context.
A unit test has been added to make sure the Zonemaster::Backend::Config module can be loaded without it being able to locate a backend_config.ini file at load time.

Clean up determination of config file default path

---

.gitignore
.travis.yml
lib/Zonemaster/Backend/DB.pm
lib/Zonemaster/Backend/DB/MySQL.pm
lib/Zonemaster/Backend/DB/PostgreSQL.pm
lib/Zonemaster/Backend/DB/SQLite.pm
share/create_db.pl
share/patch/patch_sqlite_db_zonemaster_backend_ver_8.0.0.pl
t/lifecycle.t
t/test01.t

This PR introduces rpcapi.t which is intended to host unit tests for the entire RPC-API. It also adds a feature to control the flow of time from unit tests. Finally it makes use of this feature to add a unit test for the behavior of ZONEMASTER.age_reuse_previous_test.
Fixes #758 and #761.
* The formatting commit is just there to reduce the diffs of the remaining commits.
* All questions to SQL about the current time (and some adjacent time calculations) are removed and replaced questions to Perl. It's much easier to control Perl's perception of time, and we'll be able to leverage this to be able to procedurally control time from unit tests. Fixes #758.
* Thanks to the removal of some database specific syntax we're able to deduplicate some (now identical) code in the database specific …

Control the flow of time from unit test

---

script/zonemaster_backend_testagent

Prevent crash of the TestAgent if the database becomes unavailable.
Addresses #878 
Catch database connection error when retrieving next test to run.
For the error related to #878
1. start the testagent daemon
2. stop the MySQL or PostgreSQL server
3. the testagent daemon should still be running and an error should be logged every `DB.polling_interval` seconds

Testagent survive database connection failure

---

lib/Zonemaster/Backend/DB.pm
lib/Zonemaster/Backend/DB/MySQL.pm
lib/Zonemaster/Backend/DB/PostgreSQL.pm
lib/Zonemaster/Backend/DB/SQLite.pm
script/zonemaster_backend_testagent

Remove double connection to the database on startup.
This came up as an alternative solution to a drive-by fix in #955.
This PR decouples the opening of database connections from the construction of Zonemaster::Backend::RPCAPI and Zonemaster::Backend::TestAgent instances. This allow us greater flexibility in how we can express initialization code for our daemons and it also makes the initialization code more understandable.
Run the [smoke test](https://github.com/zonemaster/zonemaster-backend/blob/develop/docs/Installation.md#61-smoke-test).

Allow DB adapter consturction without actually connecting

---

lib/Zonemaster/Backend/DB.pm
lib/Zonemaster/Backend/DB/PostgreSQL.pm

From #769 
> N.B. The database schemas still use references to NOW() in default value definitions for certain fields, but all insert queries are updated to make sure that those default values are never used.
It seems we missed some insert queries. This PR fixes that.
Follow-up on #769
Set the `creation_time` with Perl time.
Check that all `creation_time` in database are UTC.

Use Perl time on test creation

---

docs/API.md
docs/Architecture.md
docs/Upgrade.md
docs/upgrade/upgrade_zonemaster_backend_ver_8.2.0.md
lib/Zonemaster/Backend/DB.pm
lib/Zonemaster/Backend/DB/MySQL.pm
lib/Zonemaster/Backend/DB/PostgreSQL.pm
lib/Zonemaster/Backend/DB/SQLite.pm
share/patch/patch_db_zonemaster_backend_ver_8.2.0.pl

With #769 we don't use the database time and pass a time in UTC to the database. I think we were already storing date and times in UTC before. So this is just about making it explicit and use a more suitable data type.
n/a
* Modify data types in database
* Deduplicate some code (since we don't rely on databases time functions anymore)
* Provide an upgrade script to update the database (cover the N.B. from #769) 
Follow the upgrade instructions, tables schema should be properly updated.

Store times in UTC in database

---

docs/API.md

This PR updates the specification of "get_test_results()" to make it correct. The current wording must be result of some copy-and-paste error.
The "get_test_results()" will return data in the same way independent if the test was created as a single test or part of a batch.
Updates API.md. There is no change of logic.
This is documentation change only. It should be reviewed to make sure it is correct.

Corrects API.md

---

docs/API.md

The "id" field in the "result" object is leaking the PRIMARY KEY from the database. It should then be removed from the results. Furthermore there is no use of it.
In order to properly remove this field from the results, it needs to be deprecated first.
As discussed in #946, the field should be first documented as _Deprecated_.
Deprecate the "id" field from the "result" object in `get_test_results`.
Documentation only

Deprecate the result 'id' field in get_test_results

---

docs/API.md
lib/Zonemaster/Backend/DB.pm
lib/Zonemaster/Backend/RPCAPI.pm
t/test01.t

When calling "get_batch_job_result", if the batch is undefined then produce an error `Zonemaster::Backend::Error::ResourceNotFound`.
#860 
* make the domain list in `add_batch_job` non empty
* update `get_batch_job_result()` in DB.pm
* document the error message
* small cleanup: remove the `user_exists` abstraction
Can be manually tested using #860.
A new test has also been added.

Produce an error on unknown batch

---

docs/API.md
lib/Zonemaster/Backend/DB.pm
lib/Zonemaster/Backend/DB/MySQL.pm
lib/Zonemaster/Backend/DB/PostgreSQL.pm
lib/Zonemaster/Backend/DB/SQLite.pm
t/test01.t

Standardize the way datetimes are represented in results from the RCPAPI.
This work has been first conducted in #964, but due to a possible breaking change, this has been moved to another PR.
* New `created_at` field in `get_test_results` and `get_test_history` with the time represented using ISO 8601 `2022-03-28T12:07:40Z`
* Deprecate the `creation_time` field in `get_test_results` and `get_test_history`
* Update API documentation
Check that there is a new `created_at` field in the output from the `get_test_result` and `get_test_history` methods is in ISO 8601 format.

Use ISO 8601 to represent datetimes

---

lib/Zonemaster/Backend/DB.pm

* Make profile case insensitive when computing the fingerprint.
* Normalize profile name before storing it.
\-
*Lower case the profile name when projecting the params.
The following commands should return the same test id when executed
* `./script/zmb start_domain_test --domain 'zonemaster.net' --lang en --profile DEFAULT`
* `./script/zmb start_domain_test --domain 'zonemaster.net' --lang en --profile default`

Normalize profile name in DB

---

lib/Zonemaster/Backend/DB.pm

Suppress WARNING messages when value is undefined.
Appears with #972.
Always pass a defined value to `lc()` when normalizing the params.
Run the command from #972 without any profile defined, no Warning message should be logged.

Fix precedence when normalizing params

---

MANIFEST
docs/Configuration.md
docs/EnvironmentVariables.md
lib/Zonemaster/Backend/Errors.pm
lib/Zonemaster/Backend/Log.pm
lib/Zonemaster/Backend/RPCAPI.pm
script/zonemaster_backend_rpcapi.psgi
script/zonemaster_backend_testagent

Following the discussion at https://github.com/zonemaster/zonemaster-backend/pull/959#pullrequestreview-898947996 I decided to do a dedicated PR for logging.
* Replace part of #959
* Maybe address partially #214
* Drop Log::Dispatcher
* Implementation of log levels now corresponds to the documentation
* Add support for structured logging (JSON) using context and extra parameters
* `ZM_BACKEND_RPCAPI_LOGJSON=1` for RPCAPI
* `--logjson` for test agent
* Use same init function for logger from RPCAPI script and test agent
* Structured logging
`ZM_BACKEND_RPCAPI_LOGJSON=1 ZM_BACKEND_RPCAPI_LOGLEVEL=debug starman --preload-app script/zonemaster_backend_rpcapi.psgi  2>&1 | jq -crR '. as $raw | try fromjson catch $raw'`
```json
{"category":"Zonemaster::Backend::Config","level":"notice","message":" …
```

Improve loggers

---

lib/Zonemaster/Backend/DB/MySQL.pm
lib/Zonemaster/Backend/DB/PostgreSQL.pm
share/patch/patch_db_zonemaster_backend_ver_8.2.0.pl

Currently we store the index using an INTEGER in database. When using batches there is a risk we reach the upper limit.
n/a
* update database schema for PostgreSQL and MySQL
* update the database upgrade script
Run the upgrade script and check that the `id` field has the right data type

Store index using BIGINT in database

---

lib/Zonemaster/Backend/DB.pm
lib/Zonemaster/Backend/TestAgent.pm
script/zonemaster_backend_testagent
t/test01.t

When running batches, updating the `progress` while the test is running will perform a lot of unnecessary database writes which may lead to performance issues. This remove the `progress` database update for a test with a `batch_id`.
Addresses #274
Extract the `batch_id` of a test when retrieving the next test so that we can check if the test belongs to a batch or not and bypass the `progress` update or not.
Create a batch job and check that the `progress` of each test goes from 0 to 1 and then from 1 to 100 without any steps.
Create a test and check that the `progress` of the test goes from 0 to 1 and then gradually until 100.

Bypass update of "progress" for batch tests

---

script/zonemaster_backend_testagent

* Run preflight checks on both start and foreground.
Replace part of #959
* Run preflight checks on both start and foreground.
* `perl script/zonemaster_backend_testagent --logfile=- --outfile=/tmp/zonemaster_testagent.out --loglevel=debug foreground` shows the `Starting pre-flight check` log message.

run preflight on foreground

---

docs/EnvironmentVariables.md

Add missing environment variable in documentation.
https://github.com/zonemaster/zonemaster-backend/pull/966#issuecomment-1102217575
https://github.com/zonemaster/zonemaster-backend/issues/737
Add documentation for `ZONEMASTER_BACKEND_CONFIG_FILE`
\-

Improve env doc

---

script/zmb

* Do not send IP in NS if there is no IP to send
A side effect of https://github.com/zonemaster/zonemaster-backend/pull/957 is that the IP fields no longer accept the empty string as a valid value. After reading through the API documentation it appears that the empty string was never documented as being an accepted value so I do not consider it a breaking change.
* Omit IP field if it no IP was given
* `./script/zmb start_domain_test --domain zonemaster.net.  --nameserver ns2.nic.fr` should work fine again

Fix zmb as empty string is no longer accepted in IP field

---

.travis.yml
lib/Zonemaster/Backend/TestAgent.pm
share/da.po
share/es.po
share/fi.po
share/fr.po
share/nb.po
share/sv.po

Replace libidn with libidn2.
https://github.com/zonemaster/zonemaster-ldns/pull/133
* Update Travis dependency
* Replace references to "libidn" with "libidn2"
Using Zonemaster::LDNS (with libidn2 support), Zonemaster should work the same as before.

Use libidn2 instead of libidn

---

.travis.yml

By default, it seems that Travis uses Ubuntu 16.04 which does not include `libidn2`. Furthermore we [only support Ubuntu 20.04](https://github.com/zonemaster/zonemaster#Supported-operating-system-versions). Hence it should be safe to configure Travis to use [Ubuntu 20.04](https://releases.ubuntu.com/20.04/).
Travis failed in #986.
Configure Travis to use Ubuntu 20.04 (Focal Fossa).
Travis should run and pass.

Specify OS to use for Travis

---

lib/Zonemaster/Backend/RPCAPI.pm

When starting a test with `0` as domain the test does not start and a error is returned to the user:
```
./script/zmb start_domain_test --domain 0 | jq
{
"id": 1,
"error": {
"code": -32603,
"data": null,
"message": "Internal server error"
}
}
```
relevant rpcapi log entry:
```json
{
"category": "Zonemaster::Backend::RPCAPI",
"code": -32603,
"error": "Zonemaster::Backend::Error::Internal",
"level": "error",
"message": "Caught Zonemaster::Backend::Error::Internal in the `Zonemaster::Backend::RPCAPI::start_domain_test` method: No domain in parameters",
"method": "Zonemaster::Backend::RPCAPI::start_domain_test",
"pid": 70063,
"reason": "No domain in parameters\n",
"rpc_method": "start_domain_test",
"timestamp": "2022-05-02T15:06:45Z"
}
```
This PR intends to fix this issue. …

Don't die if domain is '0'

---

script/zonemaster_backend_testagent

Fix regression from #966 
\-
* remove line setting pid in context at start of test agent
* Run test agent and rpcapi
* Start a test
* Check that the pid changes when the test start (59623 and 59634 in the following example)
`perl script/zonemaster_backend_testagent --logfile=- --outfile=/tmp/zonemaster_testagent.out --loglevel=debug foreground --logjson | jq -c`
```json
{"category":"main","level":"debug","message":"Starting pre-flight check","pid":59623,"timestamp":"2022-05-02T13:21:34Z"}
{"category":"Zonemaster::Backend::Config","level":"notice","message":"Loading config: /home/gbm/workspace/zonemaster/backend_config.ini","pid":59623,"timestamp":"2022-05-02T13:21:34Z"}
{"category":"main","level":"debug","message":"Completed pre-flight …
```

Don't set pid in log context

---

lib/Zonemaster/Backend/DB.pm
lib/Zonemaster/Backend/Validator.pm
share/fr.po
t/db.t
t/test_validate_syntax.t

* NS with final dot should not make the test crash
* Having a final dot should not result in a different hash
* Domain with consecutive dots should not be accepted as valid
https://github.com/zonemaster/zonemaster-engine/issues/1055
https://github.com/zonemaster/zonemaster-backend/issues/854
* Remove final dot from domain if not root
* Remove final dot from NS
* Return an error if a domain contains consecutive dots
* `./script/zmb start_domain_test --domain zonemaster.net  --nameserver ns2.nic.fr.:192.93.0.4` should not crash
* `./script/zmb start_domain_test --domain zonemaster.net.  --nameserver ns2.nic.fr:192.93.0.4` should return the same hash id
* `./script/zmb start_domain_test --domain zonemaster..net.  --nameserver ns2.nic.fr...:192.93.0.4` should return an validation error

Fix handling of consecutive and final dots

---

lib/Zonemaster/Backend/DB.pm
lib/Zonemaster/Backend/DB/MySQL.pm
lib/Zonemaster/Backend/DB/PostgreSQL.pm
lib/Zonemaster/Backend/DB/SQLite.pm
share/patch/patch_db_zonemaster_backend_ver_8.2.0.pl
t/batches.t
t/test01.t

Store the normalized domain value in the "domain" column in database.
Follow-up of #983 
Database files.
Normalize passed "domain" in get_test_history() before retrieval (since domains are now normalized in database).
Update the upgrade script.
Unit tests are added, they should pass. Or start a test with a trailing dot to the domain (and/or with uppercase letters), the domain stored in database should be normalized.
Using the upgrade script should remove any trailing dot from the domain column, as well as down casing it.

Normalize domain column

---

script/zmb

This PR adds the --queue option to zmb's "start_domain_test" and "add_batch_job" commands.
Resolves #1002 
...
1. Keep `lock_on_queue` to default value (0).
2. Create tests with `queue` set to 5.
3. Verify that the new tests are never run.
4. Set `lock_on_queue` to 5 under `ZONEMASTER` section in backend_config.ini and restart Backend.
5. Verify that tests with `queue` 5 are run, but not tests with `queue` 0.

Allow --queue in zmb's "start_domain_test" command's options

---

lib/Zonemaster/Backend/Log.pm
script/zonemaster_backend_rpcapi.psgi

Fix logger initialization when passing an undefined level. For instance when the environment variable not present the following error messages are displayed
```
Use of uninitialized value $ENV{"ZM_BACKEND_RPCAPI_LOGLEVEL"} in lc at /home/gbm/workspace/zonemaster/zonemaster-backend/script/zonemaster_backend_rpcapi.psgi line 35, <DATA> line 1.
Argument "" isn't numeric in numeric le (<=) at /home/gbm/workspace/zonemaster/zonemaster-backend/lib/Zonemaster/Backend/Log.pm line 121, <DATA> line 1.
```
\-
* Do log level normalization after checking that it is defined
* Use default level when level is undef
* Start the RPCAPI after unsetting the log level environment variable.
```
unset ZM_BACKEND_RPCAPI_LOGLEVEL
starman --preload-app script/zonemaster_backend_rpcapi.psgi
```
* Make sure not …

fix initialization of logger when level variable is undef

---

lib/Zonemaster/Backend/DB.pm
t/lifecycle.t

After thinking about test reusability between single tests and batch tests, I do agree that we need to properly handle things. This is about making the following choice:
* a batch test is never reused
* a single test can only be reused by a single test
#979, and all discussions on whether to reuse tests or not and how 
Update a database call to exclude all tests started as batch.
A unit test is added along the PR.
---
A test can be created in two different ways:
* as a _single test_
* as a _batch test_
One of the goal of test reuse is to avoid duplicates in database and gives a quick response to similar queries. Deciding that a test can always be reused would give the following constraints:
* a _single test_ has a higher precedence and need to be executed quickly (do not wait for a whole …

Test reuse - do not reuse tests created by a batch

---

lib/Zonemaster/Backend/DB.pm
lib/Zonemaster/Backend/TestAgent.pm

The progress computation relies on parsing the logger trace which is quite heavy work. It appears that the searched values are available in the entry directly when receiving "TEST_CASE_END" message (at least).
n/a
* Fix the total number of planned methods (check that each method is part of the current profile)
* Update TestAgent.pm and the progress computation
* Provide some small refactoring (see the commits' history to follow the changes)
Tests should pass.
I've set this PR to next release, I think this is a nice improvement that removes some heavy code and computation power. However this is totally fine to move it to v2022.2 if it appears to be too short to have a proper review process.

Simplify test progress' computation

---

MANIFEST
t/TestUtil.pm
t/batches.t
t/db.t
t/idn.t
t/lifecycle.t
t/parameters_validation.t
t/test01.t

Unit testing Zonemaster::Backend might require to regularly create a new testing environment with clean database for instance. The goal is to provide a simple module that can be loaded to access common methods while testing the Backend.
n/a
* new `TestUtil.pm` module
* refactor some tests to use this new module
Tests should pass.

Provide a module for common tasks when testing Zonemaster::Backend

---

lib/Zonemaster/Backend/Log.pm

Fixes log messages not being redirected to log file when using starman.
fixes #1013
* Don't duplicate the STDERR so log message are correctly redirected.
* Changes the default log level to `info` so that the default log level in RPCAPI is the same as the one in agent.
* Imports missing dependency.
Start the RPCAPI:
```
unset ZM_BACKEND_RPCAPI_LOGLEVEL
starman --preload-app --error-log=/tmp/zm-rpcapi.log --pid=/tmp/zm-rpcapi.pid --listen=127.0.0.1:5000  script/zonemaster_backend_rpcapi.psgi
```
In another terminal start a new test:
```
./script/zmb start_domain_test --domain zonemaster.net
```
Only the pre-fork log messages should be displayed in STDERR:
```
2022-05-18T10:43:06Z [52630] [NOTICE] [Zonemaster::Backend::Config] Loading config: /tmp/zonemaster/backend_config.ini …
```

Fix log output

---

docs/Installation.md
t/lifecycle.t

This PR fixes some dependency issues and a bug that I noticed for Rocky.
N/A
* Installs OS package perl-Test-Mojo so the tests don't fail on installation.
* Fixes a bug in t/lifecycle.t that made us break an assumption made by Mojolicious.
* Installs OS packages for perl-Test-Differences and perl-Test-Exception, which we depend on as noted in #1021.
Follow the installation instruction using Rocky Linux.

Installation on Rocky

---

Makefile.PL
docs/Installation.md

* The current version of JSON Validator on Ubuntu is up to date, the note no longer applies.
* Some build dependencies are missing.
\-
* Remove JSON Validator note in Ubuntu installation
* Add Test::Difference and Test::Exception to the list of test dependencies
Installation should work.

Update installation doc

---

Makefile.PL

Some packages require newer versions for Zonemaster::Backend to be installed (especially on Centos 7 where such packages come with an unsupported version from the repositories).
n/a
Manifest.PL
Installation should work on all supported OS.

Dependencies: upgrade some versions and add a missing one

---

docs/upgrade/upgrade_zonemaster_backend_ver_8.2.0.md
share/patch/patch_db_zonemaster_backend_ver_8.2.0.pl

This PR fixes problems found during release testing.
Fixes problems introduced in #1005 and #970.
* MariaDB: Adds an instruction to back up the zonemaster database before running the migration script. This is needed because ALTER TABLE statements don't respect transactions on MariaDB.
* MariaDB: Refactors the migration code so the somewhat riskiest operation comes first. I.e. the one to add the unique constraint to users.username.
* PostgreSQL: Fixes the normalization of domain names.
1. Install Backend 8.1.0.
2. Run `zmtest zonemaster.net` and `zmtest zonemaster.net.`.
3. Install this branch of Backend on top of it. (Or current develop to reproduce the bug.)
4. Run the database migration script.
5. Run `echo "select domain from test_results;" | sudo -u zonemaster psql zonemaster`.
Before …

Fix some problems when upgrading the database to the schema for 8.2.0

---

share/patch/patch_db_zonemaster_backend_ver_8.2.0.pl

After #983 (and https://github.com/zonemaster/zonemaster-engine/issues/1055), we update the logic around trailing dots (and consecutive trailing dots). It seems that previously it was ok to run a test for a domain such as `afnic.fr...` or `...`. They would result in testing `afnic.fr` and `.`. So it's fair to clean the database to remove any trailing dots. But careful when it comes to domains composed of only dots.
documentations:
MySQL: https://dev.mysql.com/doc/refman/5.7/en/string-functions.html
PostgreSQL: https://www.postgresql.org/docs/10/functions-string.html
SQLite: https://www.sqlite.org/lang_corefunc.html#substr
Follow-up on #1030
patch script for 8.2.0
Insert domains with only 4 dots `....`. Running the patch script should normalize such domain to `.`.
In Engine it is possible …

Fix trailing dot removal in migration script

---

lib/Zonemaster/Backend/Config.pm
lib/Zonemaster/Backend/DB.pm
lib/Zonemaster/Backend/RPCAPI.pm
lib/Zonemaster/Backend/TestAgent.pm
t/db.t

Respect profile properties `net.ipv4` and `net.ipv6` in custom profiles.
* Fixes #1039.
* Meant to replace #1043 - in fact it contains those same commits.
* RPCAPI now fills in parameter defaults before recording test requests in the database.
* TestAgent now accepts the profile test parameter explicitly set to default even when it is not explicitly specified in the config.
* The DB module no longer depends on Profile.
1. Make sure your installed profile.json file has not been modified.
2. Create a custom profile with the filename `noipv6.profile` and the contents `{"net":{"ipv6":false}}`.
3. Add this line to the PUBLIC_PROFILES of your backend_config.ini: `noipv6 = /path/to/noipv6.profile`.
4. Run `zmb start_domain_test --profile noipv6 --domain alpha.example | jq -r .result`
5. Run `zmb …

Respect net.ipv4 and net.ipv6

---

docs/API.md
lib/Zonemaster/Backend/DB.pm
t/test01.t

There is no use of the database `id` since we have implemented the `hash_id`. Therefore, I think it is safe and good that we remove the `id` from the results in the `get_test_results` method.
Follows deprecation done in #949 (v2022.1).
Update the API `get_test_results` method.
A call `get_test_results` should not give the database `id` of the test, but only its `hash_id`.

Do not expose database primary key

---

script/zmtest

`zmtest` enables by default both IPv4 and IPv6. It should rather let profile setting rule, unless disabled by option.
Fixes #1040
1. Disable IPv4 or IPv6 in the default policy file (see #1039 why you currently must change there).
2. Start a test with `zmtest`
3. Verify that the selected protocol remains disabled.

Removes enabling IPv4 and IPv6 by default in zmtest

---

t/test_profile.json

Since https://github.com/zonemaster/zonemaster-engine/pull/1117, the IPV6_DISABLED message tag is lowered to DEBUG. This commit updates the testing profile so that the level for this message is always INFO. In this way the test can rely on the message.
https://github.com/zonemaster/zonemaster-backend/pull/1050#issuecomment-1227159829
Add a `logfilter` entry to `t/test_profile.json` so that `IPV6_DISABLED` message have an INFO level.
Tests should pass.

Temporarily set IPV6_DISABLED message to INFO in testing profile

---

docs/API.md
lib/Zonemaster/Backend/RPCAPI.pm
t/test01.t

This exposes the Zonemaster-LDNS version via the API call `version_info`.
Addresses https://github.com/zonemaster/zonemaster-backend/issues/790#issuecomment-1194376576
Update `version_info` to expose Zonemaster-LDNS version.
Update API.md document.
Update t/test01.t to check that `version_info` returns a value for Zonemaster-LDNS.
Make a call to `version_info` and see that the Zonemaster-LDNS version is exposed.
```
zmb version_info | jq
```

Expose Zonemaster-LDNS version

---

.travis.yml
Makefile.PL
lib/Zonemaster/Backend/Validator.pm

Remove dependency on (to be deprecated) Zonemaster::Engine::Net::IP.
In zonemaster/zonemaster-engine#1119 Zonemaster::Engine::Net::IP we're dropping support for Net::IP.
The issue zonemaster/zonemaster-engine#1129 has been created to deprecate Zonemaster::Engine::Net::IP, with the intended migration path being to use Net::IP::XS directly.
Calls into Zonemaster::Engine::Net::IP are replaced with calls into Net::IP::XS.
This change is covered by existing tests in `t/validator.t`.

Use Net::IP::XS directly

---

docs/API.md
lib/Zonemaster/Backend/RPCAPI.pm
lib/Zonemaster/Backend/Translator.pm

Make test case available in test result.
Related PR: https://github.com/zonemaster/zonemaster-gui/pull/341
Depends on: https://github.com/zonemaster/zonemaster-engine/pull/1144
* Add a `testcase` field in the object of the results array containing test case ids.
* Add a `testcase_descriptions` to map test case ids to the translated test case descriptions.
```
% ./script/zmb --server http://127.0.0.1:5000 get_test_results --test-id <testid> --lang en | jq .result.testcase_descriptions
```
```jsonc
{
"ZONE08": "MX is not an alias",
"SYNTAX05": "Misuse of '@' character in the SOA RNAME field",
"NAMESERVER06": "NS can be resolved",
"DELEGATION03": "No truncation of referrals",
"SYNTAX06": "No illegal characters in the SOA RNAME field",
"CONSISTENCY03": "SOA timers consistency",
"DNSSEC15": …
```

Add testcase results

---

script/zonemaster_backend_rpcapi.psgi

Fix `get_data_from_parent_zone` method.
Depends on https://github.com/zonemaster/zonemaster-engine/pull/1151
Manually call init method in engine.
```
% curl "localhost:5000/api" -H 'Accept: application/json' --data '{"method":"get_data_from_parent_zone","params":{"domain": "rd.nic.fr"},"id":1,"jsonrpc":"2.0"}' | jq 
```
```json
{
"result": {
"ns_list": [
{
"ip": "192.134.4.81",
"ns": "ns2.rd.nic.fr"
},
{
"ip": "2001:67c:2218:3::1:7",
"ns": "ns2.rd.nic.fr"
},
{
"ip": "192.134.0.49",
"ns": "ns3.nic.fr"
},
{
"ns": "ns3.nic.fr",
"ip": "2001:660:3006:1::1:1"
}
],
"ds_list": [
{
"digtype": 1,
"digest": "3858865db3b40bad8f00716d023ee570a8f5da8a",
"keytag": 26298,
"algorithm": 10
},
{
"algorithm": 10,
"keytag": 26298,
"digest": …
```

Fix recursor init

---

lib/Zonemaster/Backend/RPCAPI.pm
lib/Zonemaster/Backend/Translator.pm

Provide human readable message for backend generated messages.
When a test times out or dies this is how the new result UI would present the error.
* use `UNSPECIFIED` test case when no test case has been provided in message.
* convert backend message tags to human readable messages, allowing for message translation.
UI with the changes:
* Create a test and make it timeout (set timeout to a small value in backend.ini)
* Query for the test results:
```
% ./script/zmb --server http://127.0.0.1:5000 get_test_results --test-id 8c8b436b5b890c8c --lang en | jq '.result.results'
[
{
"module": "BACKEND_TEST_AGENT",
"testcase": "UNSPECIFIED",
"message": "The test was unabled to finish.\n",
"level": "CRITICAL"
}
]
```
For reference here is the ouput of this command on develop:
```
[
{
"testcase": …
```

Provide human readable messages for backend messages

---

README.md
lib/Zonemaster/Backend.pm

The statement about license in Backend.pm is not correct. In https://github.com/zonemaster/zonemaster-engine/issues/1149 @emollier pointed out the same issue for Zonemaster-LDNS and Zonemaster.Engine.
This PR updates the statement. It also updates that wording in the README file to be consistent.
This is documentation change only.

Corrects the license statement in Backend.pm

---

script/zmtest

This PR updates script `zmtest`. The main issue was that options `noipv4` and `noipv6` were not working.
```
$ zmtest --noipv4 zonemaster.net
error: method start_domain_test: Illegal value. Expects "true", "false" or "null"  at /usr/local/bin/zmb line 637.
```
Part of release testing 2022.2
Fix usage of option `--noipv4` and `--noipv6`
Add options `--help` and `-h`
Update documentation and formatting
```
$ zmtest
No domain specified
Usage: zmtest [OPTIONS] DOMAIN
[...]
```
```
$ zmtest --noipv4 --noipv6 zonemaster.net
[ ... ]
"results": [
{
"level": "INFO",
"message": "Using version v4.5.1 of the Zonemaster engine.\n",
"module": "SYSTEM",
"testcase": "UNSPECIFIED"
},
{
"level": "CRITICAL",
"message": "Both IPv4 and IPv6 are disabled.\n",
"module": "SYSTEM",
"testcase": "UNSPECIFIED"
}
], …
```

Fix zmtest script

---

docs/Installation.md

Install Plack::Middleware::ReverseProxy from an OS package instead of from CPAN.
This was done as part of release testing for v2022.2.
* One dependency is moved from `cpanm` to `dnf`.
* Some transitive dependencies are cleaned up from our installation instruction.
Covered by the usual installation testing.

Update dependencies for Rocky 8.7

---

lib/Zonemaster/Backend/RPCAPI.pm

Looking at the logs in `zm-rpcapi.log`, there are several lines like this one:
```
Use of uninitialized value $test_name in uc at /usr/local/share/perl5/Zonemaster/Engine/Translator.pm line 241. Extra parameters: {'rpc_method' => 'get_test_results'}
```
This comes from a small error in the RPCAPI code.
n/a
Pass the right variable to `test_case_description()` in RPCAPI.pm.
...

Fix uninitialized value warning in zm-rpcapi.log

---

docs/API.md
lib/Zonemaster/Backend/DB.pm
lib/Zonemaster/Backend/DB/PostgreSQL.pm
t/batches.t
t/test01.t

Remove a deprecated key. "creation_time" replaced by "created_at".
https://github.com/zonemaster/zonemaster-backend/issues/1063
* update code (DB.pm, PostgreSQL.pm)
* update documentation (API.pm)
* update tests (test01.t, batches.t)
Test should pass.

Remove deprecated "creation_time" key

---

share/GNUmakefile

New Makefile rule to create an empty PO file using the basename provided in the POLANG variable.
Same changes as in https://github.com/zonemaster/zonemaster-engine/pull/1185 and https://github.com/zonemaster/zonemaster-engine/pull/1191
Addresses https://github.com/zonemaster/zonemaster/issues/1131
* Create a new empty PO file
* Set the "Language" field with the language name
* Update the header fields with default value
* "Project-Id-Version: 1.0.0\n"
* "Language-Team: Zonemaster Team\n"
* "Content-Type: text/plain; charset=UTF-8\n"
* Automatically remove comments
Run `make POLANG=xx new-po` and check that the fields are automatically set with the default values.

Provide a rule "new-po" to create an empty PO file

---

lib/Zonemaster/Backend/DB.pm
lib/Zonemaster/Backend/Translator.pm
t/lifecycle.t

Provide better message for both cases (test died or test reached `max_zonemaster_execution_time`) instead of one global message.
https://github.com/zonemaster/zonemaster/issues/1139
* New message tag `TEST_DIED`
* Update msgid for `UNABLE_TO_FINISH_TEST`
Try with `corp.ds.fedex.com`, the output should explicitly state that the test was stopped.
```
zmtest corp.ds.fedex.com
```

Dissociate died test from reaching max execution time

---

docs/API.md
docs/Configuration.md
lib/Zonemaster/Backend/Config.pm
lib/Zonemaster/Backend/RPCAPI.pm
script/zonemaster_backend_rpcapi.psgi

The current API methods return different object types in the "result" property. In #790 it has been discussed the need to always return an object to facilitate expanding the results. It was also noted that the API methods' names could be harmonized and improved. This first work is about providing new API methods based on the discussion in #790, and deprecate all existing API methods.
This is the first step of the process:
Mapping between old and new method names:
| current method name | current top-level property | new method name | new top-level property |
| --- | :---: | --- | :---: |
| `version_info` | object | `system_versions` | object |
| `profile_names` | array | `conf_profiles` | object |
| `get_language_tags` | array | `conf_languages` | object |
| `get_host_by_name` | array | …

Always return an object from API methods and deprecate all existing API methods

---

docs/API.md
docs/Configuration.md
lib/Zonemaster/Backend/Config.pm
script/add-batch-job.pl
script/zmb
script/zmtest
script/zonemaster_backend_rpcapi.psgi
share/backend_config.ini
t/TestUtil.pm
t/batches.t
t/config.t
t/test01.t
t/test_validate_syntax.t

Second stage in the update of the RPCAPI methods. This PR updates the code and tests to use the new methods from #1054.
Follow up #1054 
* Scripts
* Unit tests
* Deprecate RPCAPI.enable_add_api_user and RPCAPI.enable_add_batch_job properties in the INI file. Emit warning if used.
* Add unit tests
* Documentation
Unit tests should pass.

RPCAPI apply new methods in code, scripts and tests

---

MANIFEST
share/GNUmakefile
t/po-files.t

New unit test to verify that PO files are correct regarding some rules:
* no fuzzy marks
* all PO files are tidied
* PO files msgid/msgstr format should be consistent 
Same checks as in Zonemaster-Engine and Zonemaster-CLI (https://github.com/zonemaster/zonemaster-cli/pull/314)
new t/po-files.t
Unit test should pass.

Unit test for PO files

---

MANIFEST
MANIFEST.SKIP
t/po-files.t

Unit tests for PO files are only relevant for CI tests, not for tests at installation. This PR removes the PO file tests from the distribution package.
Compare with https://github.com/zonemaster/zonemaster-cli/pull/320
Makes t/po-files.t not being included in the distribution package. Add comment to t/po-files.t
Make sure that Travis passes and installation works.

Removes meaningless PO file tests from distribution package (Backend)

---

.travis.yml
Makefile.PL
docs/Installation.md
lib/Zonemaster/Backend/RPCAPI.pm

Zonemaster::Backend depends on String::ShellQuote. However it seems we don't use [its functions](https://metacpan.org/pod/String::ShellQuote#DESCRIPTION) anywhere in the module. It should be safe to remove this dependency.
Remark on the `zonemaster-users` mailing list.
* Remove dependency to String::ShellQuote in the code and installation instructions
Test should pass and installation should work.

Remove dependency to String::ShellQuote

---

docs/API.md
docs/Configuration.md
lib/Zonemaster/Backend/Config.pm
lib/Zonemaster/Backend/RPCAPI.pm
lib/Zonemaster/Backend/Validator.pm
t/config.t
t/test01.t
t/test_validate_syntax.t

This PR cleans up deprecations related to LANGUAGE.locale.
It fixes #1061. It integrates a commit from #1060 which cleans up one of the deprecations.
* Feedback is improved when a unit test fails.
* Specifying languages with country code in the RPC-API is no longer supported.
* Specifying multiple locale tags with the same language code in LANGUAGE.locale is no longer supported.
* Specifying LANGUAGE.locale with an empty value is no longer supported.
* The `_clear_LANGUAGE_locale` and `_add_LANGUAGE_locale` methods are replaced with a `_set_locales` method.
* Try starting `zm-rpcapi` with LANGUAGE.locale set to an empty value.
* Try starting `zm-rpcapi` with LANGUAGE.locale including multiple locale tags with the same language code.
* Try calling RPC-API methods with a `language` argument …

Remove deprecated features related to locale

---

lib/Zonemaster/Backend/RPCAPI.pm

Fix wrong schema for method `test_progress`.
\-
Use `job_status` schema instead of `job_create` schema, as it should be.
Querying for a test progress (even a non existent test) should not return a `Invalid method parameter(s).` error.
```
$ curl 'http://localhost:5000' --data '{"jsonrpc":"2.0","id":0,"method":"test_progress","params":{"test_id":"0000000000000000"}}
{"jsonrpc":"2.0","id":0,"result":null}
```

Fix wrong schema for deprecated method

---

MANIFEST
share/zm-rpcapi.service
share/zm-testagent.service

This PR adds Systemd support.
* Rocky Linux 9 has dropped support for LSB.
* The unit files are compatible with Rocky Linux 8 and 9. They can be adapted for other operating systems later on as needed.
* While the old LSB init files are quite configurable with environment variables, the new Systemd unit files have everything hard coded. They can be updated for configurability later on as needed.
New Systemd unit files for zm-rpcapi and zm-testagent are added.
Follow the installation instruction for Zonemaster Backend in release 2023.1 on both Rocky Linux 8 and 9.

Add systemd support

---

lib/Zonemaster/Backend/Config.pm
lib/Zonemaster/Backend/RPCAPI.pm
script/add-batch-job.pl
script/zmb
script/zmtest
script/zonemaster_backend_rpcapi.psgi
share/backend_config.ini
t/batches.t
t/config.t
t/test01.t
t/test_validate_syntax.t

Remove deprecation warning and comments to all old RPC API methods and mark the new methods as experimental.
What were the deprecated methods (and old stable) are again the default stable API methods.
https://github.com/zonemaster/zonemaster/issues/1159
Relates to https://github.com/zonemaster/zonemaster-backend/pull/1054 and https://github.com/zonemaster/zonemaster-backend/pull/1083.
Revert commits where old methods were deprecated and based upon new methods. Now the experimental methods are based on the stable one.
* Unit tests should pass
* Review the code and verify that the unit tests cover the stable API
* Check that the new experimental API is working (there is currently no unit test)
* Check that changes made in Backend for this release are still working (and have not been …

Reinstate old RPC API methods

---

share/nb.po

This PR removes a fuzzy mark in the Norwegian translation, that appears to have been left in by accident after translating the corresponding sentence.
Follow-up to #1103.
Remove a “fuzzy” mark in the Norwegian translation for TEST_DIED.
Unit tests should pass.
Run the command `make -sC share show-fuzzy`. No output should be visible.

Norwegian translation: unfuzzy TEST_DIED message

---

lib/Zonemaster/Backend/DB.pm
t/batches.t

There is an artificial restriction on multiple concurrent batches with the same user, i.e. the second batch cannot be created until the first has completed. It does not give any protection on overload since a batch user can create batch with a million zones, but not two concurrent batches with 1000 each. There can be good reasons to create multiple batches if the different batches should use profile or different settings.
This PR removes the restriction. It also adjusts the unit test.
The documentation is updated in https://github.com/zonemaster/zonemaster/pull/1178
Before this PR try with the following two commands, and the second will be refused (assuming batch is accepted and `USER` is a batch user with API key `KEY`):
```
zmb add_batch_job --username USER --api-key KEY --domain iis.se …
```

Remove multiple batch restriction

---

lib/Zonemaster/Backend/DB.pm
t/idn.t
t/lifecycle.t
t/queue.t
t/test01.t

Make it possible for multiple Test Agents to process the same queue without multiple workers running the same job.
In #1115 @matsduf said:
> When a large batch is to be tested, adding several Test Agents increases performance if the server has large capacity. Several servers could also be used. One limitation is that current code only allows one Test Agent per queue. All [jobs] in a batch always belong to the same queue.
In this PR description I'm using the term "job" instead of the traditional term "test". Speaking of *the testing of jobs* is less confusing than speaking of *the testing of tests*.
However in the code changes I used the term "test" in anticipation of "the great renaming".
* Replaces #1115.
The easiest way to review this is probably to do it commit by commit.
* …

Synchronized claiming of jobs for processing

---

MANIFEST

Make MANIFEST clean.
The files were added by #1092 and #1121, respectively, but not added to MANIFEST.
Building should not complain on missing files in MANIFEST.

Adds missing files in MANIFEST

---

.travis.yml

This PR adds a missing dependency and updates the Perl versions for Travis CI.
https://github.com/zonemaster/zonemaster-engine/pull/1305
https://github.com/zonemaster/zonemaster-engine/pull/1287
* Test against Perl 5.36, 5.30 and 5.26 instead of 5.30, 5.26 and 5.16;
Travis should pass.

CI: update dependency and Perl versions

---

lib/Zonemaster/Backend/DB.pm
lib/Zonemaster/Backend/RPCAPI.pm
lib/Zonemaster/Backend/Validator.pm
share/patch/patch_db_zonemaster_backend_ver_11.0.3.pl
t/db.t
t/parameters_validation.t

Use new name normalization method instead of Basic00.
https://github.com/zonemaster/zonemaster-engine/pull/1040 introduce a new method to normalize domain names before testing. Let's use it.
It also fixes https://github.com/zonemaster/zonemaster-backend/issues/1032.
* Normalize domain name before saving to database
* Use normalized domain for history search
* Normalize domain name before fetching data from parent (fixes issue that cause that method to not work for idna domains, see https://github.com/zonemaster/zonemaster-gui/issues/426)
**Note:** With this PR, domains are normalized before being saved to database, meaning that domains that contain ulabel will be converted to alabel before saving. That might break history for the affected domains. Should we provide a migration script to …

use name normalization method

---

share/zm_testagent-bsd

On FreeBSD Perl is installed in /usr/local/bin, which is not available when a start script is started by service().
Make sure `service zm_testagent start` works in FreeBSD.

Fix PATH for testagent start script

---

lib/Zonemaster/Backend/RPCAPI.pm

This PR fixes a bug in get_test_results. The RPCAPI reference specifies that `ns` arguments should sometimes be included in the results, but this functionality was broken since last release. 
The bug was introduced in #1092 and discovered while testing #1145.
The cause of the bug is that the database schema was changed to use capitalized names instead of uppercase module names, and get_test_results was not updated accordingly.
This PR updates get_test_results to understand the new database schema.
Run `zmtest se` and see that all entries from the `Nameserver` module include an `ns` argument.

Fix ns argument

---

share/patch/patch_db_zonemaster_backend_ver_11.0.3.pl

This PR fixes translation of message strings in reports of test results that have been migrated from the previous version of the database schema.
This problem was found while release testing v2023.2. The problem is described as item 3 in https://github.com/zonemaster/zonemaster-backend/pull/1092#issuecomment-1892265157.
The migration script is updated to save module and test case names the way zm-rpcapi expects to find them.
1. Create dist tarballs for Zonemaster-LDNS, Zonemaster-Engine and Zonemaster-Backend from both the master branch and the develop branch (or the PR branch in case it hasn't been merged) and place them in the $HOME/old and $HOME/new directories.
2. Using the master branch dist tarballs, follow the installation instructions for Engine and Backend up to but excluding the …

Fix message strings in test reports after migration

---

script/zmb

This PR fixes a problem in how zmb handles UTF-8 data in its arguments.
Fixes #1138.
Arguments are received as octet string. Before this change each argument octet would be interpreted as a native character (e.g. per ISO 8859-1) and encoded into UTF-8 before being injected into the JSON-RPC request. If the arguments were already UTF-8 encoded this would result in double UTF-8 encoding. After this change the argument octets are injected in verbatim into the JSON-RPC request.
You should be able to specify domain names with U-label to zmb like this:
```sh
$ zmb start_domain_test --domain råttgift
```

Avoid double UTF-8 encoding in zmb

---

lib/Zonemaster/Backend/TestAgent.pm

This PR makes job_status and test_progress return proper percentages (instead of 1/99ths).
This PR should not be merged before the v2023.2 release.
Fixes zonemaster/zonemaster#1176.
TestAgent is made to set progress to proper percentages. Because DB::test_progress() clams the progress value to a maximum of 99, this change will not interfere with the state semantics of the progress value even when TestAgent requests a progress value of 100.
Run a job using zmtest and verify that the job finishes out at 100 percent progress with all the results included, just like it should.

Make job_status report proper percentages

---

lib/Zonemaster/Backend/RPCAPI.pm
t/rpc_validation.t

This PR updates the terminology used in experimental RPC API methods.
* Use "job id" instead of "test id", "hash id" or just "id".
* Avoid using to "frontend".
* Abbreviate cardinal "number" as "num" instead of "nb". Is "nb" a french abbreviation? It feels foreign to me. (I also considered using "no" as in №, but that's for ordinal numbers and these are cardinal numbers.)
Fixes #1084.
In the RPC API the following input and output parameters are renamed.
| RPC method | Parameter type | Old parameter name | New parameter name |
| ----------- | ----------------------- | -------------- | --------------- |
| job_status | input | test_id | job_id |
| job_params | input | test_id | job_id |
| job_results | input | id | job_id |
| job_results | output | hash_id | job_id |
| domain_history | input …

Update language in experimental RPC API paramaters

---

lib/Zonemaster/Backend/DB.pm
lib/Zonemaster/Backend/Translator.pm
share/patch/patch_db_zonemaster_backend_ver_11.2.0.pl
t/translator.t

This PR adds unit tests for `Zonemaster::Backend::Translator` and addresses an oversight in Backend caused by storing the module’s names as mixed case instead of uppercase.
Submitting PR https://github.com/zonemaster/zonemaster-engine/pull/1346 made it clear that `Zonemaster::Backend::Translator` lacked appropriate unit tests. When adding them, I found more bugs, now addressed in the same PR. I also noticed that all Backend-generated messages suddenly became untranslated.
- Add unit tests;
- Make sure future backend errors are stored as module `Backend_Test_Agent`;
- Introduce a DB migration script to fix existing entries that were missed between Backend version 11.0 (Zonemaster release 2023.2) and the next release.
**Prerequisite**: PR …

Ensure Backend’s messages stay translated

---

.travis.yml
t/translator.t

This PR makes locale being set so that translation works in `t/translator.t` in all OSs.
Travis is an exception where it has not been possible to make it work for all subtests. To prevent it from failing the script ends before all subtests have been run.
The MySQL service suddenly fails to start in Jammy, but it still works in Focal. For Postgresql Jammy must be kept.
Fixes #1173 and fixes issue with failing Mysql in Travis
* Travis must pass the first few subtests from `translator.t`.
* Every supported OSs must pass the tests when the calling environment is without locale with UTF-8 support.
* Run `printenv` to identify all set locale related keys (value being `C.UTF-8`, `C` or some other value).
* Remove all keys that have a value containing the string "utf" or "UTF".
* Run …

Fixes issue #1173 with translator.t + Downgrade Travis worker to make Mysql work

---

Makefile.PL

This PR ensures that zm-testagent doesn't fail at runtime trying to store larger test results in the database, and that the unit tests don't fail, because of a limitation in a dependency.
Fixes #1172.
On Rocky 8 and Ubuntu 20.04 the OS-provided DBD::SQLite is older than 1.66. On such systems cpanm will reject the OS package and instead pull the latest version from CPAN. The current installation instructions for Rocky and Ubuntu prescribes installing OS-packaged versions of DBD::SQLite.
We should consider what to do with the Rocky and Ubuntu installation instructions for Rocky. We have a few options, each with its own drawbacks.
1. Leave the installation instruction untouched. Users on Rocky 8 and Ubuntu 20.04 will get two versions of DBD::SQLite but only the newer one will be used.
2. …

Bump DBD::SQLite to 1.66

---

share/patch/patch_db_zonemaster_backend_ver_11.2.0.pl

This PR ensures that the database migration script for the upcoming 11.2.0 release runs on Ubuntu 20.04 by cleaning up the
Review comment on #1166: see https://github.com/zonemaster/zonemaster-backend/pull/1166#issuecomment-2194757712
Remove a handful of `use` statements from the script. None of these libraries are ever used.
Run the database migration script. Expect the script to run to completion.
**Note**: there is no need to have any test results in the database for the purpose of testing this PR.

Clean up “use” statements in database migration script for upcoming 11.2.0 version

---

Changes
Makefile.PL
lib/Zonemaster/Backend.pm

Updates files `Changes`, `Backend.pm` and `Makefile.PL`.

Preparation for release v2024.1 (Backend)

---

MANIFEST.SKIP
Makefile.PL
t/manifest.t

Run 'make distcheck' in tests.
I followed what was done in "https://github.com/zonemaster/zonemaster-engine/pull/903"
It's the same as "https://github.com/zonemaster/zonemaster-ldns/pull/195"
Fixes #765 
Make sure we don't interfere with the release process:
```
git clean -dfx   # Start out with a clean repository
perl Makefile.PL # Generate the top-level Makefile
make all         # Generate MO files and modules.txt
make distcheck   # Verify that distcheck doesn't report any missing or unrecognized files
```
Run the unit tests in the source directory:
```
make distcheck     # Make sure distcheck doesn't report any missing or unrecognized files
prove t/manifest.t # Verify the new test passes
touch new.file  # Create a file but don't add it to MANIFEST
prove t/manifest.t # Verify the new …
```

Check MANIFEST when PR is created

---

script/zmb
script/zmtest

Both `zmb` and `zmtest` are useful and have been around for several years, but being stated as experimental. Still they are referred to in documentation. Documentation update in https://github.com/zonemaster/zonemaster/pull/1303 depends heavily on them and also the installation document depend on them. Now it is high time to make then not experimental. If they will need a larger change, new script with new names can be created.
`zmb` can be used to create a batch, but the domain names have to be specified one by one with a `--domain` statement. This PR adds a file function so that the domain names in the batch can be listed in a file.
https://github.com/zonemaster/zonemaster/pull/1303, and it will be updated with the file function when this PR has been merged.
Run `zmtest zonemaster.net` …

Makes zmb and zmtest unexperimental plus adds file function to batch creation

---

MANIFEST
share/backend_config.ini
t/test_validate_syntax.t

This PR adds Slovenian language to Backend. It depends on #1185 and https://github.com/zonemaster/zonemaster-cli/pull/384 to be merged first.
When #1185 has been merged, this PR should be rebased on top. This is kept as draft until then.
#1185 and https://github.com/zonemaster/zonemaster-cli/pull/384
Verify that it works to get Slovenian translation with `zmtest` (cannot be tested before the other PRs are merged).
CC: @bzwitt

Adds Slovenian language

---

lib/Zonemaster/Backend/DB.pm

This PR changes hos historic tests are sorted. Instead of sorting by ID in the database, sorting is done by creation date of the record. If tests are never deleted or if MariaDB/MySQL is used as database the change will not create any change in sorting.
If Postgresql is used and old tests are removed, then this change will affect sorting. With this change it will be correct.
Fixes #1211
Before applying this PR:
1. Install Backend with Postgresql.
2. Create some tests of the same domain name.
3. Remove a few of the oldest.
4. Do some more tests of the same domain name.
5. Look at historic tests, and the sorting order will be wrong.
After applying this PR:
1. Install Backend with Postgresql.
2. Create some tests of the same domain name.
3. Remove a few of the oldest.
4. Do some more tests …

Sort historic tests by creation date and not ID

---

lib/Zonemaster/Backend/DB.pm
lib/Zonemaster/Backend/RPCAPI.pm
lib/Zonemaster/Backend/Validator.pm

This PR adapts Backend to the API change in zonemaster/zonemaster-engine#1316.
Should be merged together with zonemaster/zonemaster-engine#1316.
trim_space() is now invoked before normalize_name(). Prior to zonemaster/zonemaster-engine#1316 normalize_name() handled the space trimming itself.
You should still be able to include surrounding space in domain name parameters to RPCAPI calls.
```
$ zmb start_domain_test --domain ' example.com '
```

Adapt to changed Engine API

---

lib/Zonemaster/Backend/DB.pm
lib/Zonemaster/Backend/RPCAPI.pm
script/zmb
script/zonemaster_backend_rpcapi.psgi
t/batches.t

This PR implements the RPCAPI update in zonemaster/zonemaster/pull/1304.
`batch_status` was defined as an alias to `get_batch_job_result`. Now it redefined to be a smarter replacement of the old API.
Prepare a small batch (10-15 domain names) in a text file. Set down `number_of_processes_for_frontend_testing` and `number_of_processes_for_batch_testing` to a low value (e.g. 2). Start the batch with `zmb` and read the batch status with `zmb`. Read the status with various values of the optional options.

Redefines batch_status to replace get_batch_job_result
