Doc/files-description.md, Doc/zonemaster-backend-installation-instructions.md
Michal i have removed the explanation of the files and will add link into a separate file
=> Backend install instruction

Doc/zonemaster-backend-installation-instructions.md
Added commands to install SQLite
=> Appended the install instructions

Doc/zonemaster-backend-installation-instructions.md
I brought the Ubuntu 14.04 more inline with the Debian instructions. I couldn't get Store::CouchDB to work...
=> Some adjustments for Ubuntu installation

share/backend_config.ini
This is to fix the last comment in issue #29 - path to sqlite.
=> reference to sqlite is wrong

docs/installation.md
As in the commit hope this is the last effort :-)
=> Fix install1

docs/installation.md
=> Debian instructions for the backend updated

docs/API.md
Closes #104. Closes #105. Closes #106. Closes #107. Closes #108.
=> Api doc improvements

docs/API.md, lib/Zonemaster/WebBackend/DB/PostgreSQL.pm, lib/Zonemaster/WebBackend/Engine.pm
=> Misc backend fixes

lib/Zonemaster/WebBackend/DB/PostgreSQL.pm, script/add-test.pl
This has been running on @einar's machine for almost a week without any stability problems now.
=> Pg backend cleanup

LICENSE, README.md
=> modified all instances of .SE to IIS

docs/installation.md
The main features are:
* A dedicated "Dependencies" section
* A dedicated "Configuration" section
* A dedicated "Startup" section
* A dedicated "Post-installation sanity check" section
Having explicit sections for the above allows better integration with the coming
system testing documentation.
=> Add lots of structure to the installation guide

lib/Zonemaster/WebBackend/Runner.pm
=> Fixes #266, Fixes #267 - The backend no more does any DNS lookup for nameservers

lib/Zonemaster/WebBackend/DB/MySQL.pm, lib/Zonemaster/WebBackend/DB/PostgreSQL.pm, lib/Zonemaster/WebBackend/DB/SQLite.pm
Reverts dotse/zonemaster-backend#288
=> Revert "Fixes #287 - Return immediately if no domain present in get_test_history"

lib/Zonemaster/Backend/DB.pm, lib/Zonemaster/Backend/DB/MySQL.pm, lib/Zonemaster/Backend/DB/PostgreSQL.pm, lib/Zonemaster/Backend/DB/SQLite.pm, lib/Zonemaster/Backend/RPCAPI.pm, lib/Zonemaster/Backend/TestAgent.pm
Partial fix of the #213 issue - added \n to all die statements to avoid leaking system path informationPartial fix of the #213 issue - added \n to all die statements to avoid leking system path information
=> Partial fix of the #213 issue - added \n to all die statements to avoid leaking system path information

share/zm-centos.sh-mysql, share/zm-centos.sh-postgresql
Change user that runs Backend to "zonemaster" (must be created in the system).
=> Start script fix

Makefile.PL
Nothing critical. Just polish.
=> Add repo and issue tracker to metadata

docs/Installation.md
Fix installation instructions since recent updates
=> FreeBSD installation

docs/Installation.md
This is another step in my deduplication effort regarding installation-related materials.
Additional drive-by updates:
* ~Grouped together miscellaneous topics under a common topic at the end of the document.~ (Moving to a future PR)
* Gathered up some directory creation and file copying on FreeBSD.
* Replaced some `echo | tee -a` commands with `sysrc` on FreeBSD.
=> Deduplicate instructions

docs/Installation.md
Updated installation instructions with numbered headlines and a table of contents in the beginning of the file to make it easy to find relevant section and to get an overview.
=> Numbered headlines and TOC

MANIFEST, Makefile.PL, docs/Installation.md
#366 was merged without consideration to packaging. Here's a fix for that.
The first commit just sorts a couple of lists. Reviewing is probably easier when looking at the individual commits.
=> Fix packaging after #366

lib/Zonemaster/Backend/RPCAPI.pm
Fix issue #380 by adding a Regex which check the validity of a domain name.
=> Chech domain input characters

Changes, lib/Zonemaster/Backend.pm
Preparation for release 2.0.2
* Updated Changes.
* Bumped version in Backend.pm.
=> Preparation for release 2.0.2

docs/Installation.md, share/zm-backend.sh
* Skip creation of unused directories
* Create directories with appropriate privileges
* Protect database passwords from unauthorized users
* Use identical mode params to install across all platforms
* Create directories in installation instruction rather than in the service script
=> Update paths and permissions

README.md, docs/API.md, docs/Architecture.md, docs/Configuration.md
Partial fix for dotse/zonemaster#498.
I've made some assumptions here. Please check carefully.
=> Profiles doc

Changes, docs/API.md, docs/Installation.md, lib/Zonemaster/Backend.pm, lib/Zonemaster/Backend/RPCAPI.pm, share/zm-backend.sh
Synchronize the profiles branch to the latest version of the develop branch.
=> Updates from develop

docs/Installation.md, lib/Zonemaster/Backend/RPCAPI.pm
Merge current develop into profiles feature branch. No conflicts.
=> Merge develop into feature branch

docs/Installation.md
Merge current develop into profiles feature branch. No conflicts.
=> Merge develop into profiles branch

docs/API.md
Add property "filter" in get_test_history in the API documentation.
=> Update "get_test_history" with the "filter" property

docs/API.md
Reverts dotse/zonemaster-backend#407
=> Revert "Update "get_test_history" with the "filter" property"

docs/API.md
Reverts dotse/zonemaster-backend#406
=> Revert "Deprecate validate_syntax"

docs/API.md, lib/Zonemaster/Backend/DB/MySQL.pm, lib/Zonemaster/Backend/DB/PostgreSQL.pm, lib/Zonemaster/Backend/DB/SQLite.pm, lib/Zonemaster/Backend/RPCAPI.pm
Add filter property for get_test_history method
Fix issue #293
=> Update "get_test_history" with the "filter" property (from dev branch)

Makefile.PL, docs/API.md, lib/Zonemaster/Backend/RPCAPI.pm, lib/Zonemaster/Backend/Validator.pm, script/zonemaster_backend_rpcapi.psgi
Hi,
A quick Proof Of Concept of an input validation layer using JSON::Validator (cpan install JSON::Validator).
=> Add input validation layer

docs/API.md, lib/Zonemaster/Backend/RPCAPI.pm
Deprecate user_ip, user_location and location data type.
Also, removed usage and storage of these informations as ask by issue #317
=> Remove personnal information (GDPR)

MANIFEST
Update manifest with Validator.pm to fix "make dist"
=> Update manifest with Validator.pm

Changes, lib/Zonemaster/Backend.pm
* Added change log to Changes.
* Updated version number in Engine.pm to the same as the latest in Changes.
=> Updates as prepartion for release

share/zm-backend.sh
This is helpful when you want to start a development version of the service.
=> Make file locations overridable

lib/Zonemaster/Backend/RPCAPI.pm
Resolve issue #445.
With this change, filter works.
```
$ curl -sS -H "Content-Type:application/json" -d '{"jsonrpc": "2.0","id": 4,"method": "get_test_history","params": {"offset": 0,"limit": 200,"filter":"all","frontend_params":{"domain":"iis.se"}}}' http://localhost:8080/ | jq .
{
"id": 4,
"result": [
{
"overall_result": "INFO",
"id": "d6eabb1ae5e707e0",
"advanced_options": null,
"creation_time": "2018-09-17 12:25:48"
},
{
"creation_time": "2018-09-17 12:24:38",
"id": "081e94cdf1718fba",
"advanced_options": null,
"overall_result": "error"
}
]
}
```
=> Resolve issue #445

lib/Zonemaster/Backend/Config.pm, share/backend_config.ini, share/travis_mysql_backend_config.ini, share/travis_postgresql_backend_config.ini, share/travis_sqlite_backend_config.ini
Remove geolocation code. Unused code.
=> Remove geolocation code

docs/API.md, docs/Configuration.md
Documentation for #450, #451 and #452.
=> Profile updates

lib/Zonemaster/Backend/Config.pm, lib/Zonemaster/Backend/TestAgent.pm, t/test01.t
'default' profile related bugfixes of the issue #405
=> 'default' profile related bugfixes

lib/Zonemaster/Backend/TestAgent.pm, t/test_DB_backend.pl, t/test_runner.pl
New PR to add a few bugfixes to issue #405 fix
=> Fix issue 405 code part

t/test01.t, t/test_DB_backend.pl
changed 'default_profile' to 'default'
=> Fixed old 'default_profile' syntax and changed to 'default'

docs/API.md, lib/Zonemaster/Backend/Config.pm, lib/Zonemaster/Backend/Config/DCPlugin.pm, lib/Zonemaster/Backend/DB.pm, lib/Zonemaster/Backend/DB/MySQL.pm, lib/Zonemaster/Backend/DB/PostgreSQL.pm, lib/Zonemaster/Backend/DB/SQLite.pm, lib/Zonemaster/Backend/RPCAPI.pm, lib/Zonemaster/Backend/TestAgent.pm, lib/Zonemaster/Backend/Validator.pm, script/create_db_mysql.pl, script/create_db_postgresql_9.3.pl, script/crontab_job_runner/execute_tests.pl, script/patch_db_mysql_for_backend_DB_version_lower_than_1.0.3.pl, script/patch_db_postgresq_for_backend_DB_version_lower_than_1.0.3.pl, script/zonemaster_backend_rpcapi.psgi, script/zonemaster_backend_testagent, share/backend_config.ini, share/travis_mysql_backend_config.ini, share/travis_postgresql_backend_config.ini, share/travis_sqlite_backend_config.ini, t/test01.t, t/test_DB_backend.pl
We accept in the request to have a profile name with capital letters BUT we test in lowercase.
It's also based on the function "Zonemaster::Backend::Config->ListPublicProfiles()" which will be implemented soon by MTO (The function is implemented in PR #461 Commit cda24a7.).
=>  Change to unsensitive profile name check in the API #452 

lib/Zonemaster/Backend/RPCAPI.pm, script/zonemaster_backend_rpcapi.psgi
Create an API method to get the list of public profile name 'profiles_names' #450
=>  Create an API method to get the list of public profile name #450

MANIFEST
Fix issue #474 - Add docs/Configuration.md to MANIFEST
=> Fix issue #474 - Add docs/Configuration.md to MANIFEST

docs/Installation.md
This is a dependency of Backend but of neither Engine nor LDNS so it should be listed here.
=> Add forgotten dependency

lib/Zonemaster/Backend/DB/PostgreSQL.pm
Fixes the memory leak described in issue #481 
The line causing the issue is only commented out now as it was added there for a reason I can't remember.
=> Fixes issue #481 - Memory leak

docs/API.md
Modify "default_profile" for "default" which is the correct name of the default profile.
Fix #500
=> Modify "default_profile" for "default"

docs/Installation.md
I made some improvements to the installation instruction for Debian while testing.
=> Improvements to installation instruction

docs/Installation.md
Added a note on the FreeBSD package system and the need to activate and update it. Also see zonemaster/zonemaster-engine#544.
=> Update installation instructions on FreeBSD

Changes, lib/Zonemaster/Backend.pm
* Updated Changes
* Updated Backend.pm
=> Preparation for release 4.0.0

Changes, lib/Zonemaster/Backend.pm
Updates of Changes and Backend.pm, respectively.
=> Preparation for release 4.0.1

lib/Zonemaster/Backend/Config.pm, script/zonemaster_backend_rpcapi.psgi, script/zonemaster_backend_testagent, share/zm-backend.sh
This is a collection of fixes for problems indirectly related to having incorrect database configuration in backend_config.ini.
=> Error handling and logging

lib/Zonemaster/Backend/Config.pm, script/zonemaster_backend_testagent
=> Log details of terminated tests

lib/Zonemaster/Backend/Config.pm, script/zonemaster_backend_testagent
This PR was built on top of the commits from #531. That PR was merged. I'm not sure why Github keeps showing those commits in this PR. Please disregard them.
The only commit relevant for review here is 3d124b0 Shut down gracefully on SIGTERM.
Fixes #532.
=> Graceful shutdown for TestAgent

script/zonemaster_backend_testagent
Fixes #557.
Should work but I haven't tested it much.
=> Fix warning in test agent daemon

MANIFEST, README.md, docs/upgrade-from-1.0.x-to-1.1.x.md, docs/upgrade-from-4.0.x-to-5.0.x.md, docs/upgrade-to-1.0.3.md
* Updated the upgrade instructions in README to handle multiple upgrades (issue #558)
* Updated the upgrade instructions file under `docs/` (issue #558)
* Added two upgrade instructions files under `docs/` for two upgrades (issue #558)
* Added the latest upgrade files (issue #555) to MANIFEST
=> Resolve issue 555 and 558

lib/Zonemaster/Backend/DB/PostgreSQL.pm
=> Fixes #570 - UTF-8 issue for idn domain names

lib/Zonemaster/Backend/DB.pm
When testing #525 it seems there is an use JSON::PP missing
=> Added missing use JSON:PP

docs/Configuration.md, lib/Zonemaster/Backend/Config.pm
* Corrected POD in code
* Corrected links in documentation
=> Corrected config documentation

share/zm-rpcapi.lsb
Fixes #591.
Again I have only tested this on Ubuntu. I don't have a good CentOS installation to test on at the moment. Sorry about that.
=> Inline Ubuntu implementation of status_of_proc

.travis.yml
An update in preparation for release 2019.2.
=> Update supported Perl versions in Travis

MANIFEST
Adding files missing in the MANIFEST file list
```
matsd@u1604base:~/git/zonemaster-backend$ make distcheck
"/usr/bin/perl" "-Iinc" "-MExtUtils::Manifest=fullcheck" -e fullcheck
Not in MANIFEST: docs/upgrade-from-4.0.x-to-5.0.x.md
Not in MANIFEST: docs/upgrade-to-1.0.3.md
```
=> Missing files added

docs/Installation.md
=> Avoid rerunning unrelated tmpfiles configs

docs/Installation.md
* Updated with all direct dependencies
* All direct dependencies available as binary package installed with `pkg install`
* Direct dependency not available as binary package explicitly listed to be installed by `cpanm`
=> Installation document updated for FreeBSD

docs/Installation.md
* Removed "--password" to remove prompting for empty password
* Inserting full path to make independent of working directory
=> Updates of instruction for Debian/Ubuntu

lib/Zonemaster/Backend/DB.pm
=> Fix warning in test agent

.travis.yml, Makefile.PL, docs/Installation.md
Install binary package for Try::Tiny on Debian/Ubuntu.
=> Install binary package for Try::Tiny on Debian/Ubuntu

share/zm-rpcapi.lsb, share/zm_rpcapi-bsd
=> Add log level setting to RPCAPI start script

docs/Installation.md
Small fixes in the documentation.
=> Fixes in documentation

docs/Installation.md
Some updates primarily for FreeBSD
=> Update installation instruction

Changes, Makefile.PL, lib/Zonemaster/Backend.pm
* Changes: Updated with changes since last release.
* CLI.pm: Release version
* Makefile.PL: Updated dependencies
=> For release v2020.1 (Backend)

Changes, lib/Zonemaster/Backend.pm, t/test01.t
Created following the [merge-develop-branch-into-master] instructions.
[merge-develop-branch-into-master]: https://github.com/zonemaster/zonemaster/blob/develop/docs/internal-documentation/maintenance/ReleaseProcess-release.md#12-merge-develop-branch-into-master
=> Merge develop into master (Backend)

MANIFEST, lib/Zonemaster/Backend/DB.pm, lib/Zonemaster/Backend/DB/MySQL.pm, lib/Zonemaster/Backend/DB/SQLite.pm, lib/Zonemaster/Backend/RPCAPI.pm, script/add-batch-job.pl, script/add-test.pl, script/create_db_sqlite.pl, t/test01.t
First version of full support for SQLite fixes #179
=> Fix issue 179

docs/Installation.md
These are corrections and simplifications I made during installation testing for MariaDB and PostgreSQL. See commit messages for
=> Update CentOS installation instruction

docs/Installation.md
With this change I can successfully run the smoke test with SQLite.
=> Fix SQLite DB file ownership

docs/Installation.md
Make the services come up after reboot on CentOS.
=> Make Backend start automatically when booting

docs/Installation.md
Next release brings stable SQLite support.
=> Update SQLite note

lib/Zonemaster/Backend/Validator.pm
=> Accept empty IPs in nameserver objects

docs/API.md, docs/Configuration.md, docs/Installation.md, share/backend_config.ini, share/travis_mysql_backend_config.ini, share/travis_postgresql_backend_config.ini, share/travis_sqlite_backend_config.ini
Resolves issue #711 and assumes that https://github.com/zonemaster/zonemaster-engine/pull/880 is merged.
=> Adds fi_FI to supported languages in RPCAPI

.gitignore, CONTRIBUTING.md
Resolves issue #669.
The purpose of this PR is to make sure we have something meaningful to say to CPAN users.
=> Adds CONTRIBUTING (Backend)

Changes, Makefile.PL, lib/Zonemaster/Backend.pm
Updates:
* Backend.pm with new version (6.2.0)
* Changes
* Makefile.PL (updated dependency)
There are many good improvements here classified as "fixes". They are mostly seen if you dive into the code.
=> Prepares for release of v2021.1 (Backend)

share/zm-rpcapi.lsb, share/zm_rpcapi-bsd
This is a backport of #851 for the fix release.
See #851.
=> Backport #851 (Load config only once)

Changes, lib/Zonemaster/Backend.pm
For release of v2021.1.3
Updates "Changes" and sets version number in "Engine.pm".
=> Preparation for release v2021.1.3

Changes, Makefile.PL, docs/Configuration.md, docs/Installation.md, lib/Zonemaster/Backend.pm, lib/Zonemaster/Backend/Config.pm, lib/Zonemaster/Backend/Validator.pm, script/zonemaster_backend_rpcapi.psgi, share/backend_config.ini, share/zm-rpcapi.lsb, share/zm_rpcapi-bsd
Merge the updates in v2021.1.3 branch into master branch.
=> Merge fix-release-v2021.1.3 into master (Backend)

Changes, lib/Zonemaster/Backend.pm
Make the develop branch have the same content of the `Changes` file and the `Backend.pm` file as the master branch.
This PR give the same changes as 116ceb0e4aacd08983d12866858c567a4360adeb and 598fcc62fba44b4802aa1f773ee190c36f30b368, where the latter takes precedence of the former.
Updates:
* Changes
* Backend.pm
=> Updates Changes and Backend.pm with updates for release v2021.1.3 (Backend)

docs/Configuration.md, docs/Installation.md, docs/upgrade/upgrade_zonemaster_backend_ver_8.0.0.md
Update installation instruction
* Replace Centos by Rocky Linux
* Replace yum by dnf
* Install all debian dependencies using binary packages
* install the backend, run the tests
=> Update installation doc

share/da.po, share/es.po, share/fi.po, share/fr.po, share/nb.po
This PR creates and updates PO files but nothing that affects translation.
* Update header of fr.po to conform to zonemaster model
* Create empty PO files for languages that are missing
Nothing to test.
=> Create and update PO files

docs/upgrade/upgrade_zonemaster_backend_ver_8.0.0.md
Add missing instruction in upgrade document
* clean old patch files
* fix path to patch for sqlite
* fix mysql upgrade
follow upgrade document
=> Update upgrade doc

docs/Installation.md
Update the Rocky installation instruction.
Done as part of installation testing for v2021.2.
Adds a note to ignore warnings and changes a couple of yum to dnf.
Perform installation test.
=> Update Rocky installation instruction

lib/Zonemaster/Backend/RPCAPI.pm
This PR means to ensure that all exceptions thrown inside the RPCAPI handler methods get handled by handle_exception(). Previously there were some spots where exceptions would not be properly caught. Instead they would be returned to the RPCAPI client and not show up in the log file.
Fixes #914.
All of the business logic in the RPCAPI handler methods is moved in under the covered of eval+handle_response. Before only most of it was.
Some of the moved lines could not possibly throw exceptions, but I moved them into the eval blocks anyway because it's just simpler to have everything inside them without making exceptions.
In one case I replaced a call to handle_exception() with a call to die(). This is because you must not have a handle_exception() inside the eval block of another …
=> Maximize the reach of eval+handle_exception

Changes, Makefile.PL, lib/Zonemaster/Backend.pm
* Bumps version in perl module
* Updates Changes file
* Updates requirement in Makefile.PL to latest version of Engine
Updated files:
* Changes
* lib/Zonemaster/CLI.pm
* Makefile.PL
=> Preparation for release v2021.2 (Backend)

share/da.po
This PR...
Fixes #909 
Add danish translation
...
=> Add danish translation

lib/Zonemaster/Backend/Metrics.pm
Fix issue accessing hash
See mailing list
=> improve code quality

share/es.po
This PR adds a first version of the spanish translation.
Fixes #910 
Just share/es.po. I tried to add this file to MANIFEST but it only contains the .mo files.
New language addition.
=> First translation to spanish language

docs/API.md, docs/Configuration.md, docs/Installation.md, share/backend_config.ini, share/travis_mysql_backend_config.ini, share/travis_postgresql_backend_config.ini, share/travis_sqlite_backend_config.ini
This PR adds Spanish
Nothing should break. Engine must be updated before any translation will be seen in messages.
=> Adds Spanish language (es_ES) to various places

docs/Upgrade.md
Add instructions for upgraders.
Documentations only.
=> Update Upgrade.md for the release

Changes, Makefile.PL, lib/Zonemaster/Backend.pm
Updated files:
* Changes
* Makefile.PL
* lib/Zonemaster/Bakend.pm
=> Preparation for v2021.2.1 release (Backend)

t/lifecycle.t
This PR automates the checking of cancellation messages in crashed and timed out tests.
Fixes the last remaining part of #546 that wasn't already implemented in #769.
Adds a couple of tests to lifecycle.t.
Just run `make test`.
=> Check for cancellation messages in lifecycle.t

docs/Configuration.md, lib/Zonemaster/Backend/Config.pm
Fix broken links since removal of deprecated properties in #954.
n/a
docs/Configuration.md
Documentation only.
=> Fix links in (and to) configuration sections

lib/Zonemaster/Backend/DB.pm, lib/Zonemaster/Backend/TestAgent.pm
* Avoid code duplication.
* Avoid extra call to database
n/a
Update "DB.pm" file
Internal change only, nothing should break.
=> Deduplicate database call

MANIFEST, t/batches.t, t/idn.t, t/test01.t
This is a first step towards better test coverage for batch feature.
#952 
new `t/batches.t` file
tests should pass
=> Testing batch feature

docs/EnvironmentVariables.md
Document testing environment variables
#737
Documentation
Documentation only
=> Document testing environment variables

lib/Zonemaster/Backend/DB.pm, lib/Zonemaster/Backend/DB/MySQL.pm, lib/Zonemaster/Backend/DB/PostgreSQL.pm, lib/Zonemaster/Backend/DB/SQLite.pm
Avoid code duplication. Use standard SQL, do not rely on PostgreSQL JSON parsing.
n/a
DB.pm, DB/MySQL.pm, DB/PostgreSQL.pm and DB/SQLite.pm files
Internal change only, tests should pass.
=> Deduplicate "get_test_history" code

t/batches.t
Improve test coverage.
n/a
Unit test only.
Unit test should pass.
=> Unit test for duplicated user insertion

share/es.po
This PR updates es.po spanish translation file according to request for upcoming release.
Fixes #1018 
share/es.po
=> Update spanish translation file for upcoming release, ticket #1018

docs/API.md, docs/Configuration.md
This PR updates the deprecation information in API and Configuration to have correct information for the release.
Review the information.
=> Updates deprecation information

Changes, Makefile.PL, lib/Zonemaster/Backend.pm
Updates for release v2022.2.
Updates Changes, Makefile.PL and Engine.pm.
This PR will not pass the CI tests until https://github.com/zonemaster/zonemaster-ldns/pull/163 has been merged.
Review Changes and inspect Makefile.PL and Engine.pm.
=> Updates for release v2022.2 (Backend)

Changes, Makefile.PL, lib/Zonemaster/Backend.pm
Updates for release v2022.2.1.
Updates Changes, Makefile.PL and Backend.pm.
Review Changes, and inspect Backend.pm and Makefile.PL
=> Updates for release v2022.2.1 (Backend)

Changes, Makefile.PL, lib/Zonemaster/Backend.pm
Prepares for release v2022.2.2
Updates the following files:
* Changes
* lib/Zonemaster/Engine.pm
* Makefile.PL
Review.
=> Preparation for release v2022.2.2 (Backend)

t/test01.t
A unit test fails in the current develop branch. This PR fixes that.
Make a unit test less picky about which test module a test message is associated with.
Verify that it passes CI.
=> Fix broken test

share/da.po, share/es.po, share/fi.po, share/nb.po, share/sv.po
This PR updates translations to Danish, Spanish, Finnish, Norwegian and Swedish, respectively.
Resolves #1099 (partly) and #1101
The PO files.
Review the PO files.
=> Update translations (Backend)

Changes, Makefile.PL, lib/Zonemaster/Backend.pm
Updates files `Changes`, `Makefile.PL` and `CLI.pm`.
=> Preparation for release v2023.1.3 (Backend)

Changes, Makefile.PL, lib/Zonemaster/Backend.pm
See https://github.com/zonemaster/zonemaster/blob/develop/docs/internal/maintenance/ReleaseProcess-release.md#15-merge-develop-branch-into-master
=> Merge Releases/v2023.1.3 into Master (Backend)

Changes, Makefile.PL, lib/Zonemaster/Backend.pm
Updates files `Changes`, `Makefile.PL` and `CLI.pm`.
=> Preparation for release v2023.1.4 (Backend)

Changes, Makefile.PL, lib/Zonemaster/Backend.pm
See https://github.com/zonemaster/zonemaster/blob/develop/docs/internal/maintenance/ReleaseProcess-release.md#15-merge-develop-branch-into-master
=> Merge Releases/v2023.1.4 into Master (Backend)

Changes, Makefile.PL, lib/Zonemaster/Backend.pm
Updates files `Changes`, `Backend.pm` and `Makefile.PL`.
=> Preparation for v2023.2 release (Backend)

Changes, lib/Zonemaster/Backend.pm
Preparation for release (fix).
Updates files `Changes` and `Backend.pm`.
=> Preparation for v2023.2.1 release (Backend)

.travis.yml
This PR updates the Travis configuration file when it comes to Perl versions to be tested. The versions have been taken from the update in https://github.com/zonemaster/zonemaster/pull/1270
Review.
=> Update perl version to be tested by Travis (Backend)

Changes, Makefile.PL, lib/Zonemaster/Backend.pm
This PR is a preparation for v2024.2 release.
*  Changes
* lib/Zonemaster/Backend.pm
* Makefile.PL
Review.
=>  Preparation for v2024.2 release (Backend)

Changes, Makefile.PL, lib/Zonemaster/Backend.pm
This PR is a preparation for v2024.2.1 release.
*  Changes
* lib/Zonemaster/Backend.pm
* Makefile.PL
Review.
=> Preparation for v2024.2.1 release (Backend)

Changes, MANIFEST, Makefile.PL, lib/Zonemaster/Backend.pm, share/backend_config.ini, share/fr.po, share/sl.po, t/test_validate_syntax.t
https://github.com/zonemaster/zonemaster/blob/develop/docs/internal/maintenance/ReleaseProcess-release.md#15-merge-develop-branch-into-master
This PR needs no review.
=> Merge release branch into master (Backend)

share/nb.po
This PR holds updated (purged) translation to Norwegian for the backend.
There is no issue reported that this PR fixes, but after doing a general refresh of the language translations for engine, cli and backend there were some old translations that is not used anymore and therefore are purged.
Ref after doing the "./update-po nb.po" in the share directory.
...
...
=> Norwegian translation update 2025-04
